### ISSUE TITLE
Add simple image zoom to Product Detail Page

### ISSUE THREAD

**Issue by philippsauer** [intershop/intershop-pwa#1011]
**Is your feature request related to a problem? If yes, please describe it.**

Repetitive task in customer projects

**Describe the desired solution.**

Example: https://inta-live-ish18-sharkclean-ca.sharkninja.com/products/shark-rocket-duoclean-with-self-cleaning-brushroll-corded-stick-vacuum-zidZS360C?view=grid

[AB#74233](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/74233)

**Comment by M-Behr** [comment]
Design: https://www.figma.com/file/hhwgC5tho5ewHafC1zYehM/Product-Image-Zoom?node-id=27%3A585
