### ISSUE TITLE
Reduce number of error translation keys handled in the PWA

### ISSUE THREAD

**Issue by dhhyi** [intershop/intershop-pwa#1032]
Currently the localization cleanup script keeps all translations that have `.error` in the key. Most of them are probably unused. Many new APIs properly report errors already.

Try to only keep error translations that actually need to be kept in the PWA.

[AB#74643](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/74643)

**Comment by shauke** [comment]
Check the possible candidates listed here: https://github.com/intershop/intershop-pwa/commit/ecaf7138668a292dba0e9070b092e679a17d3047

**Comment by SGrueber** [comment]
Error keys have already been reduced meanwhile. There should not be a larger number of unused error keys any more.
