### ISSUE TITLE
Set language based on browser setting

### ISSUE THREAD

**Issue by rkarl-ish** [intershop/intershop-pwa#104]
**Is your feature request related to a problem? If yes, please describe it.**

Users should automatically see the storefront in their preferred language if possible. 

**Describe the desired solution.**

If the users enters the storefront and the browser locale is equal to one that is supported by the storefront, it should be used by default by the storefront. In case the user wants a different language, she can easily switch th the desired locale via language switch.

**Describe alternatives you've considered.**

**Provide additional context.**

**Comment by 5t3v3n-H** [comment]
Recommendation: use language switch.
