### ISSUE TITLE
Product Warranties

### ISSUE THREAD

**Issue by shauke** [intershop/intershop-pwa#1062]
Implement Product Warranties in the PWA similar to the Responsive Starter Store (see http://pwa-public-demo.test.intershop.com/INTERSHOP/web/WFS/inSPIRED-inTRONICS-Site/en_US/-/EUR/ViewProduct-Start?SKU=5777062&CategoryName=1584&CatalogID=Home-Entertainment).

![image](https://user-images.githubusercontent.com/50741106/157668587-9f555748-5037-4fe6-8e40-673b6d9fd27f.png)

[AB#75155](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/75155)

**Comment by SGrueber** [comment]
The basket REST api 1.x has currently some limitations. Warranties cannot be saved properly at the basket. See also [AB#72298](https://dev.azure.com/intershop-com/Products/_workitems/edit/72298)

**Comment by shauke** [comment]
IAD: https://dev.azure.com/intershop-com/Products/_workitems/edit/75146
