### ISSUE TITLE
Second punchout doesn't work

### ISSUE THREAD

**Issue by DiverDori** [intershop/intershop-pwa#1071]
**Actual Behavior**
Trying a second cxml punchout doesn't work, an error page occurs.

**Expected Behavior**
No error page.

**Steps to Reproduce the Bug**

1. Create a punchout session via setup request (customers/<customerno>/punchouts/cxml1.2/setuprequest)
2. go to created session link (http://localhost:4200/punchout?<somemoreparams>)
3. add some items to basket and transfer cart
4. Create another punchout session via setup request
5. go to created session link --> error page

**Environment Details**

- Desktop: \*
  - OS: Windows
  - Browser: Firefox
  - Project Code Version: current develop

**Additional Context, like Screenshots, Log File Snippets etc.**
It seems that the cookies might be a problem. After removing all cookies, including "punchout_BasketID", it worked again. 

[AB#75331](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/75331)

**Comment by MaxKless** [comment]
@Eisie96 is this still an issue or did #1109 fix it?

**Comment by DiverDori** [comment]
I cannot reproduce it anymore, so I guess it is solved.
