### ISSUE TITLE
Nginx exposes source maps in production

### ISSUE THREAD

**Issue by jstein213** [intershop/intershop-pwa#1176]
INFO: solution from #1127 : npm run build angular configuration production adds source maps (*.js.map) to for PWA browser and SSR. 

**Actual Behavior**
If environment variable SOURCE_MAPS has one of the values `1`, `on`, `true` or `yes` , then :
- PWA exposes source maps in browser
- PWA SSR exposes source maps to web clients, i.e. search engine crawler / robot (SEO)
else 
- PWA exposes source maps in browser
- PWA SSR exposes NO source maps

**Expected Behavior**
If environment variable SOURCE_MAPS has one of the values `1`, `on`, `true` or `yes` , then :
- PWA exposes source maps in browser
- PWA SSR exposes source maps to web clients, i.e. search engine crawler / robot (SEO)
else 
- PWA exposes NO source maps in browser
- PWA SSR exposes NO source maps

**Steps to Reproduce the Bug**

1. Go to PWA Home Page
2. Open Web Browser Dev Tools > Sources
3. Search for typescript file api-token.ts. The search returns a search hit unexpectedly.

**Environment Details**

- Desktop: \*

  - OS: Windows 10
  - Browser:  chrome / brave
  - Project Code Version : gib branch master on 31 May 2022

[AB#77148](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/77148)

**Comment by jometzner** [comment]
@jstein213 You're referring to the wrong pull request id in your bug description.

**Comment by jstein213** [comment]
> @jstein213
> 
> The SSR container sends 404 when the SOURCE_MAPS feature is turned off:
> 
> https://github.com/intershop/intershop-pwa/blob/13186643f5e5a986f0280b0e0c9958acbd1b925b/server.ts#L273-L279
> 
> The nginx will then relay those 404s, and not expose the source maps.

No. Maybe theoretically, your assumption is true. Unfortunately, live test results contradict your assumption.

**Comment by jstein213** [comment]
> @jstein213 You're referring to the wrong pull request id in your bug description.

@jometzner What is the expected correct reference? Remove it? What do you suggest to fix?

**Comment by jometzner** [comment]
> > @jstein213 You're referring to the wrong pull request id in your bug description.
> 
> @jometzner What is the expected correct reference? Remove it? What do you suggest to fix?

I already fixed it for you. Nothing needs to be done by you.

**Comment by jstein213** [comment]
@shauke @dhhyi I confirm your test results. The bug is invalid and I close it.
