### ISSUE TITLE
Folder "projects"

### ISSUE THREAD

**Issue by bankai14** [intershop/intershop-pwa#1206]
Can you explain to me the usefulness of the "projects" folder at the root of the PWA?

[AB#78089](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/78089)

**Comment by shauke** [comment]
The basic idea of the projects folder was to extract functionality that could be used in a standalone manner in other contexts besides the Intershop PWA. This could be imagined for the B2B User Management and the Requisition Management functionality which resulted in their extraction to the projects folder. In the end in the PWA it is an additional concept of adding lazy loadable functionality in a specific way.

The projects functionality was introduced with PWA version 0.22.0.
Starting for example the Organization Management as a standalone application was achieved like this.
```
ng serve --project organization-management
```
Unfortunately the standalone project starting is in current versions no longer working and would need some investigation. We obviously did not use it as much as we intended to in this way yet.
