### ISSUE TITLE
Product filters vanish when refreshing the page with logged in state

### ISSUE THREAD

**Issue by dhhyi** [intershop/intershop-pwa#1232]
**Steps to Reproduce the Bug**

1. Go to https://intershoppwa.azurewebsites.net/
2. Log in
3. Navigate to a PLP (product listing)
4. See filters on the left side
5. Refresh the page
Actual: filters vanish
Expected: filters visible

[AB#78587](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/78587)

**Comment by shauke** [comment]
Race condition. We need to implement a handling where the user login is completed before triggering any content/catalog related REST calls (cue: AppInitializer).
