### ISSUE TITLE
Performance: Improve hydration on browser side in SSR mode

### ISSUE THREAD

**Issue by philippsauer** [intershop/intershop-pwa#1308]
**Is your feature request related to a problem? If yes, please describe it.**

When running the PWA in SSR mode, the initial delivery and rendering of app is very fast. Unfortunately, after the SSR response has been rendered by the browser, much of the content will disappear for a short time (blank page with header and footer) before it is entirely rendered by the browser again. The issue can be reproduced on the inTRONICS Homepage, that contains lots of CMS content, as well as on any category and product pages.

In the best case, the user will notice this process as "flickering". But if there is lots of rendering work to do by the browser, the app can feel very slow initially.

This technically unnecessary re-initialization of the app on browser side results in low performance on client side because too much JavaScript code needs to be re-executed, content re-rendered, styles painted etc.. 

**Describe the desired solution.**

At the moment, the SSR response contains an app state, that contains product-, category- and CMS data that should be sufficient for the browser. During rehydration of the app, the browser side application should use the state data from the SSR response and avoid dispatching of unnecessary actions that cause this issue. This includes product and category requests etc.

**Provide additional context.**

* Flickering Issue: This has been repeatedly discussed in customer projects, but a solution to this is not really economically doable.
* Performance: This is also a reoccurring topic in customer projects. This feature would help to drastically improve the performance during app initialization
* The SSR response and its state can be visualized by disabling JavaScript in the browser. The state object will be part of the HTML response

[AB#80481](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/80481)

**Comment by jometzner** [comment]
Fixing this would mean messing with Angular's way of handling SSR. Maybe migrating to Angular 16 and switch on the new SSR developer preview would help the issue?

https://blog.angular.io/angular-v16-is-here-4d7a28ec680d

**Comment by SGrueber** [comment]
Should get better after Angular is updated to version 16

**Comment by kepek** [comment]
👍  Any plans/eta regarding bumping pwa to ng16?

**Comment by SGrueber** [comment]
Yes, I already worked on this and will create a PR soon
