### ISSUE TITLE
Why you're using imports in TypeScript files which are pointing to node_modules of dev dependency directly?

### ISSUE THREAD

**Issue by kepek** [intershop/intershop-pwa#1377]
**Is your feature request related to a problem? If yes, please describe it.**

The problem isn't related to anything specific, it is more a question that has been already asked here in PR #1084

https://github.com/intershop/intershop-pwa/pull/1084

**Describe the desired solution.**

While playing with intershop-pwa as part of npm workspace I just discovered some troubles while building schematics. Mostly while typescript couldn't find some dependencies.

**Describe alternatives you've considered.**

I was wondering why you're not using direct imports from rxjs as it was previously.

Now: 
```ts
import { switchMap } from '@angular-devkit/core/node_modules/rxjs/operators';
```

Before:

```ts
import { switchMap } from 'rxjs/operators';
```

**Provide additional context.**

It is in the context of npm workspaces and general monorepo idea.

[AB#83987](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/83987)

**Comment by kepek** [comment]
I'm just thinking loud here, wouldn't be better to abstract `intershop-schematics` and publish it in npm as a completely separate dependency so it could be devDependency for `intershop-pwa`?

**Comment by shauke** [comment]
> I'm just thinking loud here, wouldn't be better to abstract `intershop-schematics` and publish it in npm as a completely separate dependency so it could be devDependency for `intershop-pwa`?

Could be a good idea but it is currently not a priority. Maybe it becomes one if we would need our schematichs for more than this one project.
