### ISSUE TITLE
Reporting a vulnerability

### ISSUE THREAD

**Issue by igibek** [intershop/intershop-pwa#1413]
Hello! 

I hope you are doing well! 

We are a security research team. Our tool automatically detected a vulnerability in this repository. We want to disclose it responsibly.  GitHub has a feature called **Private vulnerability reporting**, which enables security research to privately disclose a vulnerability. Unfortunately, it is not enabled for this repository. 

Can you enable it, so that we can report it? 

Thanks in advance! 

PS: you can read about how to enable private vulnerability reporting here: https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

[AB#85209](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/85209)

**Comment by SGrueber** [comment]
Hi @igibek, I enabled the 'private vulnerability reporting'. Thank you for contacting us and reporting the vulnerability.
