### ISSUE TITLE
Npm version 9.5.0 is incompatible with Docker when userns-remap feature is enabled

### ISSUE THREAD

**Issue by tbouliere-datasolution** [intershop/intershop-pwa#1416]
Since version 4.0.0, pwa uses npm 9.5.0.
Is this incompatible with systems that use the docker userns-remap feature (https://github.com/npm/cli/issues/5900)?

The Azure App Service uses this type of functionality.
This leads to strange runtime errors like this one during the docker extraction phase

```bash
ERROR - failed to register layer: Error processing tar file(exit status 1): Container ID 1389985163 cannot be mapped to a host IDErr: 0, Message: failed to register layer: Error processing tar file(exit status 1): Container ID 1389985163 cannot be mapped to a host ID
```

We have fixed this on our projet by updating the node image node:18.16.0-alpine.

[AB#85447](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/85447)

**Comment by shauke** [comment]
Please cherry pick this commit to solve the issue in 4.0.0 based projects.
https://github.com/intershop/intershop-pwa/commit/35adb46c97fd1c166a78131a8ade45a8c268a185

The fix will be part of the 4.1.0 PWA release.
