### ISSUE TITLE
Error code 500 [Error] Server Error (5xx) - When opening tab notifications in another language

### ISSUE THREAD

**Issue by PWATEST95** [intershop/intershop-pwa#1446]
**Actual Behavior**

After creating a product notification in german PWA, opening "Notifications" tab in "My Account" section with usage in english PWA leads to an error page.

**Expected Behavior**

The "Notifications" tab displays your price notification.

**Steps to Reproduce the Bug**

1. Use the **german** B2C PWA Storefront (description still with the english terms)
2. Login
3. Choose a product e.g on of the "Featured Products" and click on it
4. Click "Price Notification"
5. Set up a price and click "OK"
6. Go to "My Account"
7. Click on "Notifications" -> everything works fine
8. Switch the language to "English"
9. Click on "My Account"
10. Click on "Notifications" -> error page appears

**Environment Details**

  - OS: Windows 10 Enterprise
  - Browser: Google Chrome, version 114.0.5735.110
  - Project Code Version: Intershop Progressive Web App 4.0.0 

**Additional Context, like Screenshots, Log File Snippets etc.**

<img width="960" alt="image" src="https://github.com/intershop/intershop-pwa/assets/135978774/d2dfa979-640c-4447-b062-4b3a43403713">

**Note** Clicking on "Price Notification" again on any product in the english PWA leads to the same error. If you than still try to add a price into the popup an additional error appears. Watch:

<img width="957" alt="image" src="https://github.com/intershop/intershop-pwa/assets/135978774/21a81c70-1d8d-4b34-ace3-cdc2973de0e6">

[AB#86730](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/86730)

**Comment by SGrueber** [comment]
The problem can only be solved in the ICM - that's why it isn't handled here any more, but in the Azure ticket [AB#86730](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/86730)
