### ISSUE TITLE
Question: What is the idea behind the encapsulation principles when it comes to declaredComponents?

### ISSUE THREAD

**Issue by kepek** [intershop/intershop-pwa#1466]
Hello,

I am not sure where I should go for `intershop-pwa` related questions so I'm sorry in advance if this is the wrong place. But I have one question regarding encapsulation principles.

There are `exportedComponents` and `declaredComponents` in ShellModule/SharedModule (obvious).

I'm trying to understand what rule/idea is behind those. Would be nice if all of the declared components would be exported since they can be accessed from the outside. 

For example, if you wish to have access to them from a completely customized ShellModule which wants to use some of the declared components - with the current setup it will not work.

What are the chances to exposing/exporting all declared components? I don't see any reason why they're private since it is just a limitation when it comes to customization.

Best regards,
Michal

[AB#88083](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/88083)

**Comment by SGrueber** [comment]
Hello @kepek,
we export only the components that are used by other modules or components, because this can help to reduce the size of the application and improve performance.
Exporting all components in the pwa could lead to performance issues and that's why we are not going to do this. 
If you have proposals for the export of some single specific components we can discuss it in our team and export them nevertheless. 
And yes, feel free to use this place here to ask question. :-)

**Comment by kepek** [comment]
@SGrueber, an example use case is when you want to have full control of your app. We have a customer who forces us to do a huge amount of customizations, but a the same time we would love to use a lot of OOTB components that you've created.

We have a custom shell module that brings some new things but a the same time client uses cms includes which are handled via lazy components ( LazyContentIncludeComponent,  LazyMiniBasketContentComponent, LazySearchBoxComponent) and they're tightly coupled with ShellModule and can't be used outside of it.

**Comment by shauke** [comment]
Hi @kepek,
after further discussion of your use case we decided not to export the lazy ShellModule components so they can be used elsewhere.
If you need for example the LazyContentIncludeComponent anywhere else than in the ShellModule you should import the SharedModule and use the ContentIncludeComponent.
If you need the LazyContentIncludeComponent in a CustomShellModule then our intended way would be to completely override the ShellModule with the standard override mechanism and import everything you need in that overridden custom ShellModule. It is not our intention to import the ShellModule in any other module to use its components.
