### ISSUE TITLE
Provide possibility for Nginx cache invalidation after staging

### ISSUE THREAD

**Issue by philippsauer** [intershop/intershop-pwa#1513]
**Is your feature request related to a problem? If yes, please describe it.**

In order to reach certain performance goals, we are forced to increase the nginx cache time to 24h. That works well but has downsides: Despite a nightly staging, changes in the CMS are not reflected immediately in the cache and can take up to 24h to become visible, depending on when the related cache entry was created. Unfortunately, this is not acceptable for the customer.

**Describe the desired solution.**

We want to be able to (automatically) trigger nginx cache invalidation without involving Dev or a DevOps Engineer. 

1. Ideally, there would be two modes: full or channel-specific. Currently, the cache keys are hashed which would make this difficult, maybe they could be prefixed with an identifier that points to a certain channel?
2. Also, it should be possible to somehow automate this invalidation. (E.g. via a scheduled job etc.)
3. Bonus: The invalidation can be triggered via ICM, like the channel page cache

**Provide additional context.**

FYI: There is a related feature request in the Helm chart repository: During Deployments, the cache needs to be invalidated manually by restarting the Memcached container to prevent broken pages, see Helm Chart Issue: https://github.com/intershop/helm-charts/issues/410

[AB#89722](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/89722)

**Comment by dhhyi** [comment]
At the moment this is a deployment topic that has to be handled by Operations. If you want a nightly cache clear, you have t schedule it with operations.
Implementing a secure way to expose an endpoint for clearing cache is a security nightmare and also depends heavily on the deployment, as per default the cache is not shared and you cannot safely reach all endpoints synchronously.

The Memcached deployment PR is experimental and already closed and will be replaced by #1509. With redis you can configure caches per deployment and clear them individually. If using a cloud service cache busting can be done securely that way.

**Comment by shauke** [comment]
There are currently no other solutions planed besides the suggested solution from Danilo. Especially with the custom shared memcached solution no further development is planed.
If the official shared Redis Cache is used and the suggested solution is not working further discussions might be needed.
