### ISSUE TITLE
Order history enhancements

### ISSUE THREAD

**Issue by ximmw** [intershop/intershop-pwa#1514]
Order history is missing the following features:
- order list: search/filtering by date range, orderno, status, productno
- order details: add2cart button
- currently order history is visible for the current user only. Optional configuration in backoffice to display order history for all users of the current customer

[AB#89758](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/89758)

**Comment by shauke** [comment]
* order list: search/filtering by date range, orderno, status, productno - implemented with #1571 
* order details: add2cart button - implemented with #1592

* order history for all users of the current customer - the REST API for this feature will be available with ICM 12.1.0 and the functionality will be implemented in the PWA, the feature will be available based on a certain permission of the currently logged in user
