### ISSUE TITLE
Remove media-feature-range-notation rule

### ISSUE THREAD

**Issue by pierredelobel62** [intershop/intershop-pwa#1526]
When this rule is activate the `@media screen and (max-width: 992px)` are changed to `@media screen and (width <= 992px)`
But this code doesn't work on many version of iOS (iOS 16 for example)
Please add `"media-feature-range-notation": null` in the stylelint configuration

**Comment by DilaraGueler** [comment]
@pierredelobel62 Thanks for letting us know that the "media-feature-range-notation" rule is causing problems on certain iOS versions. We've tried to replicate the problem on our end, but unfortunately, we weren't able to reproduce it. Could you please provide more details or steps to help us understand the issue better?
