### ISSUE TITLE
Bug when forcing product image to use L size. Product images data are not returned for products that only have the L image

### ISSUE THREAD

**Issue by dlakaistk** [intershop/intershop-pwa#1535]
**Actual Behavior**

Force L size image for product listing as well (scaling handled by third party service) by `    <ish-product-image imageType="L" [link]="true"></ish-product-image>
`
on product-tile.component.(customization).html

Displays a not found image even though L size has been forced.

**Expected Behavior**
Use the L image 

**Steps to Reproduce the Bug**

**Additional Context, like Screenshots, Log File Snippets etc.**

![image](https://github.com/intershop/intershop-pwa/assets/151643261/9e9c6cad-a768-41e5-ac1a-09dbb5e72268)

The second product below has a L size image
![image](https://github.com/intershop/intershop-pwa/assets/151643261/b4285434-8192-4c76-be6a-3f92ca299b2e)

[AB#91367](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/91367)

**Comment by SGrueber** [comment]
If you want to see L images on product listings (family pages, search pages) you have to request the L image links by the ICM server. You can do this by changing the product-list-attributes.ts file, replace 'image' by 'image@L'. 
Find more information in the Product&Categories [Swagger Docu](https://support.intershop.com/kb/index.php/Display/3N1063#l1385)

**Comment by dlakaistk** [comment]
Hi @SGrueber 

Thanks for the helpful tip and correcting the issue tag. I had a question, why is the second item in the attached screenshot not providing the L image in the output? Has it something to do with the backoffice and not the PWA?

**Comment by SGrueber** [comment]
@dlakaistk The product listing REST call doesn't return all images for a product from the ICM but only one image of a certain size. In the standard PWA this is size 'M'. So 'L' images cannot be shown. In my previous answer I described how you can change this and use 'L' images on product lists in your project. - For performance reason we cannot fetch all product information on listing pages in opposite to the product detail page.

**Comment by dlakaistk** [comment]
Thanks @SGrueber
