### ISSUE TITLE
Active Filter Facets are removed after clicking "Show all" in the filters section

### ISSUE THREAD

**Issue by philippsauer** [intershop/intershop-pwa#1572]
**Actual Behavior**

Active Filter Facets are removed after clicking "Show all" in the filters section

**Expected Behavior**

Clicking "Show all" or "Show less" does not influence the filter selection

**Steps to Reproduce the Bug**

1. Go to any product list page, e.g. https://intershoppwa-b2c.azurewebsites.net/specials/top-sellers-ctgSpecials.TopSellers
2. Click on 'Microsoft' in the brands filter section
3. Click on 'Show all' in the brands filter section
4. See error: 
-> Microsoft filter is removed from the selection
-> Same issue happens after clicking 'Show less' 

**Environment Details**

- Desktop: 
  - OS: Windows 10
  - Browser [e.g. chrome, safari], Version [e.g. 22] Chrome (latest)
  - Project Code Version: 5.0.0

[AB#92706](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/92706)

**Comment by bilelfeki** [comment]
hello @DilaraGueler can I work with you on this issue
