### ISSUE TITLE
Demo Servers for Pull Requests

### ISSUE THREAD

**Issue by dhhyi** [intershop/intershop-pwa#160]
**Is your feature request related to a problem? If yes, please describe it.**

For an easier functional review, it would be best if proposing a Pull Request would also spin up a demo server running the code of the current Pull Request.

**Describe the desired solution.**

A simple deployment could be made to the Azure Cloud with a cost-efficient AppService.

**Describe alternatives you've considered.**

Also possible would be to have a Review Server managed somewhere else, maybe on the corporate web with access from the outside.

**Provide additional context.**

- first part supplied by #321 
  - no nginx
  - App Services on Free service plan

**Comment by shauke** [comment]
It might be a good idea to switch from the review server comments:
![image](https://user-images.githubusercontent.com/50741106/111167624-9ae72300-85a1-11eb-8d6b-b7fd9b21c6b4.png)

to something similar like the environments/deployments?
![image](https://user-images.githubusercontent.com/50741106/111167721-adf9f300-85a1-11eb-909d-597f4ed8852a.png)

**Comment by shauke** [comment]
The original intend of this issue is solved good enough so that it is closed.
The additional idea to switch from comments to environments is saved in a Technical Depth (https://github.com/intershop/intershop-pwa/projects/4#card-57096939).
