### ISSUE TITLE
"NG0912: Component ID generation collision detected."  after generating a new override component

### ISSUE THREAD

**Issue by dlakaistk** [intershop/intershop-pwa#1618]
After I updated to 5.0.0. I noticed warnings on the console. Is there anyway to supress this? Related issue: https://github.com/angular/angular/issues/50158

**Actual Behavior**
`NG0912: Component ID generation collision detected.` Errors on the console

**Expected Behavior**
No warnings to be seen

**Steps to Reproduce the Bug**

1. Generate a TS override of a component
2. Restart application
3. Open Devtools
4. See warning

**Environment Details**

  -5.0.0 (Angular 16)

**Related issue**
https://github.com/angular/angular/issues/50158

**Additional Context, like Screenshots, Log File Snippets etc.**
![image](https://github.com/intershop/intershop-pwa/assets/151643261/14d6d171-a0fe-457f-96dc-1c2d7cb992d6)

[AB#95294](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/95294)

**Comment by andreassteinmann** [comment]
A lot of Angular developers are complaining about these warnings but it seems there is no simple solution to get rid of them, yet. 
- https://github.com/angular/angular/issues/50158
- https://github.com/analogjs/analog/issues/844

So if you use the component customization concepts for component TypeScript files the way as described above you have to accept the warnings at the moment. The warning is only shown in development - and not production - mode. 

The suggested solution https://angular.io/errors/NG0912 does not work.

As recommended in our documentation https://github.com/intershop/intershop-pwa/blob/develop/docs/guides/customizations.md you could also create a custom component if you have to change a lot of the component functionality. Small changes you could handle in the original source file and mark them with `// CUSTOMIZATION` comments. In both cases you would prevent the warnings.

**Comment by dlakaistk** [comment]
Hi @andreassteinmann 

Thanks for the response. We want to avoid touching the core files as much as possible. Hopefully we will have way to supress for get rid of the warnings in the future. Right now just to declutter during development we just filter  out the warnings from console. P.S: I've mislabeled this issue as `bug`. You can close this issue if you want

**Comment by andreassteinmann** [comment]
Hi @dlakaistk ok, 
thank your the fast response. Let's see if there will be an fix in future.
We will close it.
