### ISSUE TITLE
Identifier 'productMasterSKU' is not defined

### ISSUE THREAD

**Issue by ThomasRichterISH** [intershop/intershop-pwa#169]
**Actual Behavior**

When opening the file: product-detail.component.html and navigating to
      <ish-product-variation-select
        *ngIf="isVariationProduct(product)"
        [productMasterSKU]="product.productMasterSKU"
        [variationOptions]="variationOptions"
        (selectVariation)="variationSelected($event)"
      ></ish-product-variation-select>

I get a warning that "'Identifier for productMasterSKU' is not defined" 

**Expected Behavior**
 
 No warning at all.

**Steps to Reproduce the Bug**

1. Go to 'product-detail.component.html' using Visual Studio Code
3. Scroll down to '<ish-product-variation-select...'

**Environment Details**

*Desktop: *
 - OS: [e.g. iOS] CentOS
 - Browser [e.g. chrome, safari], Version [e.g. 22]
 - Project Code Version 0.17.0

*Smartphone: *
 - Browser [e.g. stock browser, safari], Version [e.g. 22]
 - Project Code Version

**Additional Context, like Screenshots, Log File Snippets etc.**

**Comment by Sebastian-Haehnlein** [comment]
slow (virtual) environment?

**Comment by ThomasRichterISH** [comment]
> slow (virtual) environment?
possibly? How can I find out?

**Comment by ThomasRichterISH** [comment]
It is kind of weird, because that seems to be the only complaint.

**Comment by Sebastian-Haehnlein** [comment]
does your taskmanager peak out?

**Comment by Sebastian-Haehnlein** [comment]
> It is kind of weird, because that seems to be the only complaint.

i think your evironment is very slow, so you have to wait until every extension of vscode is ready.
you can disable the jest extension temporary.

**Comment by ThomasRichterISH** [comment]
ok, i give that a try.

**Comment by dhhyi** [comment]
I can also see that error, but it is "just" reported by the VSCode extension, not actually the angular compiler.

It happens because `ProductView | VariationProductView | VariationProductMasterView` do not _all_ have the property `productMasterSKU`. We could possibly change the type to `AnyProductType`, but this will lead to a real compile error in the corresponding test.

**Comment by dhhyi** [comment]
It seems like we'll probably get to that when we are [Upgrading to Angular 9](https://github.com/intershop/intershop-pwa/projects/6) 😅 
https://auth0.com/blog/angular-9s-best-hidden-feature-strict-template-checking/

Stay tuned! 😉

**Comment by dhhyi** [comment]
By enabling "strictTemplates": true in "angularCompilerOptions" in tsconfig.json, this error will be detected by the compiler.

**Comment by dhhyi** [comment]
resolved by #403
