### ISSUE TITLE
Server side rendering: deviceType

### ISSUE THREAD

**Issue by nickyhaze** [intershop/intershop-pwa#171]
Hello,

I was wondering if it's possible to detect the device on the server in some sort of way? It's now always 'mobile' by default, is there a reason for this?

Regards,
Nicky Haze - Incentro

**Comment by dhhyi** [comment]
Hi @nickyhaze,
sorry, this issue somehow slipped our attention. 😅 
We are going to talk about it in tomorrow's daily for sure.

**Comment by dhhyi** [comment]
You're right, currently the device type is always set to mobile, as we figured that most shop users will access the shop with mobile devices and this follows the "mobile first" approach.

We thought about it and the best way to have a device detection in place would be to add it to the nginx (something like this https://gist.github.com/perusio/1326701) and provide an additional URL parameter for the server-side rendering. This way the nginx could then also cache different page responses for mobile and desktop versions.
