### ISSUE TITLE
Resetting includes, pagelets and pages

### ISSUE THREAD

**Issue by ivobrands** [intershop/intershop-pwa#249]
Hello,

I was wondering why the includes, pagelets and pages are reset after logging out? This happens in there effects. The reset of the components will result into blank components.

**Comment by shauke** [comment]
Hi,
the reason for resetting the the whole CMS content after logout is the possibly stored personalized content (see  #156). This was addressed with #158 and the intended behavior after deleting the content is to refetch it without personalization.
So we will have to check if this refetching is for some reason not working as intended.
Thanks for your pointing that out.

**Comment by shauke** [comment]
We tested the content loading and resetting on logout and login and could not reproduce your described issue with the blank components. So far we could not see a problem. Can you provide some more details when this occurs (PWA version, ICM version, steps to repeat)?

**Comment by ivobrands** [comment]
I see a difference between the 'https://intershoppwa.azurewebsites.net/home' and our own project. When the test PWA logs out, you will see a "@ngrx/router-store/cancel" action. This is missing in our project when we are logging out, so our content pages are only reset and not loaded after that. Do you know where this "@ngrx/router-store/cancel" is dispatched?

**Comment by dhhyi** [comment]
> Do you know where this "@ngrx/router-store/cancel" is dispatched?

The mechanism of logging out is implemented by navigating to a [`/logout`](https://github.com/intershop/intershop-pwa/blob/b573e18ac2da9e8829fb41cbb1365cd0dc0c16d2/src/app/pages/app-routing.module.ts#L117-L119) route, that is guarded by the [`LogoutGuard`](https://github.com/intershop/intershop-pwa/blob/b573e18ac2da9e8829fb41cbb1365cd0dc0c16d2/src/app/core/guards/logout.guard.ts#L20-L24). The LogoutGuard is cancelling the routing to `/logout` and redirecting to `/home`. So you should always see the cancel action.
We migrated to `@ngrx/router-store` in version 0.19 with #167.
