### ISSUE TITLE
User Management | Add/Edit User - Base Version

### ISSUE THREAD

**Issue by Sebastian-Haehnlein** [intershop/intershop-pwa#260]
Implementation of "Add User" modal. No Role assignment (maybe set default to "buyer"), no budget

**Comment by franciscomdrito** [comment]
Implementation of the basic read only User List View (only display of user name, no search, pagination, no actions etc.)
- [x] Store
- [x] Facade
- [x] Service
- [x] Component
- [x] Styling
- [x] Tests
- [x] Error Handling (b2b permission denied, visibility b2c)
