### ISSUE TITLE
Cookies with `SameSite=None` need to be set with `Secure` too

### ISSUE THREAD

**Issue by shauke** [intershop/intershop-pwa#276]
Browsers like Mozilla Firefox and Google Chrome start to inform the user that cookies that are set to `SameSite=None` need to be set to `Secure` as well. This is currently not the case in the PWA so one gets a lot of warning logs in the browser console for the cookie handling. This needs to be adapted.

Firefox
>Cookie “apiToken” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

Chrome:
>A cookie associated with a cross-site resource at http://x.y.z/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

Note
* a new cookies library could be used to address this issue:
https://github.com/stevermeister/ngx-cookie-service#set-name-string-value-string-expires-number--date-path-string-domain-string-secure-boolean-samesite-lax--strict--none--void
* Server Side Rendering support is necessary (https://github.com/stevermeister/ngx-cookie-service/issues/1)

**Comment by MaxKless** [comment]
This is not an issue with cookies set by the PWA itself as it only concerns cookies you intend to use as third-party cookies on other websites.
Some cookies from google analytics and youtube lead to this warning but this is out of our control as you are only responsible for cookies from your own domain. 
There is an issue filed with youtube concerning this: https://issuetracker.google.com/issues/151754736

**Comment by shauke** [comment]
Firefox is still complaining, just for the record. We need to keep this in mind I guess.

![image](https://user-images.githubusercontent.com/50741106/99496658-08c56a00-2975-11eb-8ba6-67ea1721162e.png)
