### ISSUE TITLE
Filters broken on Audio equipment category page

### ISSUE THREAD

**Issue by willemevertse** [intershop/intershop-pwa#327]
**Actual Behavior**
On the Audio equipment category page you dont see any filters on the left side.

https://intershoppwa-b2b.azurewebsites.net/Audio-Equipment-catpresentation-conferencing.audio-equipment?view=grid

The rest call to filters give a bad request (400) response.

**Expected Behavior**
You should see a list of sub-categories on the left side, like on this page:

https://intershoppwa-b2b.azurewebsites.net/Tablets-catComputers.897 

**Steps to Reproduce the Bug**

1. Go to http://localhost:4200/Audio-Equipment-catpresentation-conferencing.audio-equipment?view=grid
4. See error in console

**Environment Details**

- Desktop: 
  - OS: all
  - Browser chrome
  - Project Code Version

**Comment by willemevertse** [comment]
Hi Sebastian, Stefan
I see now that categories that don't have any subcategories produce this error. Example : network / firewalls has this too.
So this might be a bug in the ICM filter rest endpoint. Don't know if this is still the correct channel to report this bug in. I'm happy to submit a bug to support if you like.

regards Willem

**Comment by Sebastian-Haehnlein** [comment]
Hi,

we are currently working on the integration of the new filter rest endpoint.

https://github.com/intershop/intershop-pwa/pull/148

http://pwa-gh-review-148-universal-b2b.azurewebsites.net/Plasma-Panels-catComputers.3001.903?view=grid
