### ISSUE TITLE
Monorepo

### ISSUE THREAD

**Issue by davthu** [intershop/intershop-pwa#335]
Would be nice to separate the PWA parts in to self contained modules in a Monorepo. This way much of the core functionality could be maintained and updated separately

**Introduce tools to use a monorepo with Narvel https://nx.dev/angular**

**Comment by rkarl-ish** [comment]
Thank you for the feedback. This is rather a mid- to long term topic that we might consider for the future.

**Comment by shauke** [comment]
Issue closed since the topic Monorep is currently not in discussion.
