### ISSUE TITLE
[FR] Sitemap.xml support

### ISSUE THREAD

**Issue by rkarl-ish** [intershop/intershop-pwa#35]
**Is your feature request related to a problem? If yes, please describe it.**

In order to provide search engines the ability to crawl relevant pages easily, it is intended to provide a sitemap.xml for crawling, containing URL´s of the relevant pages (category pages, product detail pages, content pages) 

Additionally, the sitemap could contain hreflang information to better support multi language/country scenarios.

**Comment by shauke** [comment]
https://github.com/intershop/intershop-pwa/blob/develop/docs/guides/nginx-startup.md#access-icm-sitemap
