### ISSUE TITLE
Personalization group (s)pgid is missing in request call for top level categories

### ISSUE THREAD

**Issue by kapilmishra-evident** [intershop/intershop-pwa#351]
In current version, an API call is there from method _getTopLevelCategories_ in categories.service.ts to fetch top level categories to display on home page.

**Actual Behavior**
Mentioned call doesn't include personalized group parameters in URL (s)pgid. If I change line 47 of categories.service.ts file to include sendSPGID parameter as  

`return this.apiService.get('categories', { **sendSPGID: true**, params }).pipe(`
spgid  gets added to the request, but with _undefined_ value.

![image](https://user-images.githubusercontent.com/50987367/88840501-e13b6d80-d1dc-11ea-85ab-e17b7397788c.png)

**Expected Behavior**
Personalization parameter should be included in top level categories call with correct value.

**Steps to Reproduce the Bug**

1. Go to PWA homepage
2. Login with valid account.
3.  Navigate to home page again and check top level categories call in developer console.
4. Notice URL is missing with personalization group (s)pgid parameter.

To me it seems pgid get set in store after the call to top level categories made. So for mentioned call pgid is always undefined. But for subsequent calls to sub-categories and products valid pgid is present in store and Urls.

**Comment by rkarl-ish** [comment]
Hi Kapil,
thank you for raising this bug. Currently we only support personalization of CMS content in PWA out of the box. Personalization of products, prices and categories is one of the next topics we want to address but currently it is not in progress. We are going to handle this issue once we work on personalization in a larger context.

**Comment by shauke** [comment]
Converted to feature request.
