### ISSUE TITLE
Version varaition attribute filter doesnt work on B2B shop

### ISSUE THREAD

**Issue by willemevertse** [intershop/intershop-pwa#382]
**Actual Behavior**
There are no variation filter options for version on the AEG pdp 
https://intershoppwa-b2b.azurewebsites.net/Telephones/AEG-ECLIPSE-skuM5012786030527-catnetworks.phones?view=grid

**Expected Behavior**
You should see at least 2 options : 15 / 10
the rest api returns these options

**Steps to Reproduce the Bug**

Go to the PDP of the AEG product
https://intershoppwa-b2b.azurewebsites.net/Telephones/AEG-ECLIPSE-skuM5012786030527-catnetworks.phones?view=grid
Click on the version dropdown box
There are no options in the dropdown box

**Environment Details**

- Desktop: \*

  - OS: linux
  - Browser chrome
  - Project Code Version

**Comment by shauke** [comment]
Thank you for reporting this issue. We will have a look at the problem.
Maybe it can be solved with our planed rework of the variation filtering functionality that should now rely on the changed filter REST API. Currently we use some client side logic for that that should be done by ICM REST calls.
