### ISSUE TITLE
False styling and missing product names in cart adjustment messages on empty page

### ISSUE THREAD

**Issue by M-Behr** [intershop/intershop-pwa#438]
**Actual Behavior**
Product keys are displayed in messages.
The messages and the item description in table are center-aligned.
The product name in the table is bold.

**Expected Behavior**
Product names are displayed in messages.
The messages and the item description in table are left-aligned.
The product name in the table is not bold.

**Steps to Reproduce the Bug**

1. Add a product to the cart
2. Go to the backoffice and set this product to 'Out of Stock'
3. Go back to the cart and click 'Checkout'
4. See info and error messages

**Environment Details**

- Desktop: \*

  - OS: Windows 10
  - Browser: Chrome
  - Project Code Version: PWA 0.24 (public demo server)

**Additional Context, like Screenshots, Log File Snippets etc.**
![Cart_Adjustments_Empty_page](https://user-images.githubusercontent.com/66066967/97149424-06ecfa00-176d-11eb-90c4-ea76aa50fb8e.png)

**Comment by SGrueber** [comment]
see also ICM ticket IS-31294
