### ISSUE TITLE
demo site gives Error code 500

### ISSUE THREAD

**Issue by 127001** [intershop/intershop-pwa#452]
Wanted to test something on the demo site, but https://intershoppwa.azurewebsites.net currently redirects to https://intershoppwa.azurewebsites.net/error with:

`Something Went Wrong
We are sorry ...
Please go back to the Home Page and try again.

Error code 500
[Error] Server Error (5xx) `

**Comment by rkarl-ish** [comment]
Hi Jarno,
we are currently updating our Demo ICM and have some issues with that. I hope it is going to be up and running by the end of the day.

Regards,
Robert

**Comment by 127001** [comment]
Seems it has been solved @rkarl-ish , closing this issue.
