### ISSUE TITLE
PLP filters break when opening Sign In popup

### ISSUE THREAD

**Issue by franciscomdrito** [intershop/intershop-pwa#468]
**Actual Behavior**

PLP filters have an inconsistent behavior, when selecting a filter and after, opening the sign in popup, the filters either works, lose the selection or all filters disappear (specially if we refresh the page). The behavior of the product list itself seems to be ok, but filters wont reflect it. Seems a concurrency issue, maybe caused by cancelling the routing when opening the sing in button.

**Expected Behavior**

The sign in popup shouldn't affect the behavior of the PLP in general

**Steps to Reproduce the Bug**

1. Go to Navigation and Select Computers
2. Select Tablets
3. Select Acer
4. Select filter Price 1000 > 
5. Click sign in and close popup (sometimes happens the first time, sometimes we need to do more than once, seems a concurrency issue)

**Environment Details**

- Desktop: \*

  - OS: Windows 10
  - Browser Chrome
  - 0.25
**Additional Context, like Screenshots, Log File Snippets etc.**

![image](https://user-images.githubusercontent.com/62572390/100090556-3ade3c80-2e4b-11eb-8de7-b27d13c5dd82.png)

After clicking the sing in button and closing it without logging in:

![image](https://user-images.githubusercontent.com/62572390/100090923-d40d5300-2e4b-11eb-81bf-6fe4a6565bdd.png)

or in sometimes (or when refreshing): 

![image](https://user-images.githubusercontent.com/62572390/100091039-0028d400-2e4c-11eb-8fc9-85b7ac3c7894.png)

[AB#80093](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/80093)

**Comment by shauke** [comment]
Comment from @dhhyi regarding PR #696 (closed and we are open for a better solution):
> I also don't think take(1) is a solution here.
I think the problem is the select(selectQueryParams) in determineParams$, as it will start firing when the routing is started. Postponing it unto successful navigation should be the solution.
