### ISSUE TITLE
[FR] Dynamic Branding

### ISSUE THREAD

**Issue by rkarl-ish** [intershop/intershop-pwa#49]
It should be possible to dynamically change the branding within one PWA instance, e.g. exchange logo and color scheme. Dynamically, meaning no separate deployments are needed for the different brandings. This should be handled by on deployed PWA that can be configured (similar to the feature toggles) to use one or another branding.

*Possible solution*
* https://dev.to/adamaso/angular-6-dynamic-themes-without-a-library-2e9c
* https://coryrylan.com/blog/theming-angular-apps-with-css-custom-properties
* https://medium.com/free-code-camp/how-to-create-themes-for-your-angular-7-apps-using-css-variables-69251690e9c5

Other ideas are welcome.

**Comment by shauke** [comment]
The pull request is an adaption of the multiple themes support idea from https://medium.com/better-programming/angular-multiple-themes-without-killing-bundle-size-with-material-or-not-5a80849b6b34

**Comment by liquid-tadan** [comment]
is the documentation for this new feature available somewhere?

**Comment by dhhyi** [comment]
> is the documentation for this new feature available somewhere?

@liquid-tadan Not in its entirety. We have documented the usage as part of our customization guide [here](https://github.com/intershop/intershop-pwa/blob/develop/docs/customizations.md#start-customization).

As a practical example, the current code provides two themes (under [`src/styles/themes`](https://github.com/intershop/intershop-pwa/tree/develop/src/styles/themes)), a default and a blue one. We are using it for providing a different style for the inTRONICS B2C and B2B storefront which you can change in between with a button in the header of our [public deployment](https://intershoppwa.azurewebsites.net/).

More documentation will probably follow soon, as we are currently reorganizing our documentation structure.
