### ISSUE TITLE
Variation Master - Different buttons are displayed on tile view, list view and product detail page

### ISSUE THREAD

**Issue by M-Behr** [intershop/intershop-pwa#492]
**Actual Behavior**

Variation master displays different "Add to..." options on different pages. See the following descriptions:

Family Page - Tile View: Compare and "Add to Order Templates" are displayed.
![Variation Master - Tiles](https://user-images.githubusercontent.com/66066967/103552357-10e95280-4eac-11eb-9bd4-ae67719ba4a5.png)

Family Page - List View: "Add to Quote Request", Compare and "Add to Order Templates" are displayed.
![Variation Master - List](https://user-images.githubusercontent.com/66066967/103552450-38401f80-4eac-11eb-9495-d78ab00999ed.png)

Product Detail Page - No "Add to..." options are displayed.

**Expected Behavior**

A variation master has some differences to a regular product. Therefore no "Add to..." options are displayed for a variation master. See responsive starter store as reference.
Please remove "Add to Quote Request", Compare and "Add to Order Templates" button on the family page.

**Steps to Reproduce the Bug**

1. Open 'inTRONICS Business'
2. Go to category 'HOME/COMPUTERS/TABLETS/MICROSOFT'
3. See variation master product, e.g. 'Microsoft Surface Book 2'

**Environment Details**

  - Version: PWA 0.26

**Comment by dhhyi** [comment]
will be solved with #403

**Comment by dhhyi** [comment]
> will be solved with #403

http://pwa-gh-review-403-universal-b2b.azurewebsites.net/sku201807231
http://pwa-gh-review-403-universal-b2b.azurewebsites.net/catComputers.897.897_Microsoft?view=grid
http://pwa-gh-review-403-universal-b2b.azurewebsites.net/catComputers.897.897_Microsoft?view=list
