### ISSUE TITLE
SEO: Support Meta Tags for Static Content Pages

### ISSUE THREAD

**Issue by philippsauer** [intershop/intershop-pwa#505]
**Is your feature request related to a problem? If yes, please describe it.**

The configuration parameters for the CMS Meta Tags (Title, Description, Keywords) of the Static Content Page Component are being ignored by PWA. Instead, the DisplayName of the Page is being used as Title.

**Describe the desired solution.**

Meta Tags (Title, Description, Keywords) of static content pages, when configured via CMS, will be correctly set in the page header.

**Comment by dhhyi** [comment]
it's available as `configurationParameters` on the first pagelet:
![image](https://user-images.githubusercontent.com/23452927/107207352-804ce780-6a00-11eb-95f6-075f163e3095.png)
