### ISSUE TITLE
Auth0 loses session when opening new tab

### ISSUE THREAD

**Issue by franciscomdrito** [intershop/intershop-pwa#512]
**Actual Behavior**

After login into the PWA if we open a new tab in a page that doesn't require login (auth0) the session will be lost. The user will have the sign in button available and after clicking the page will then refresh and the user will be logged.

**Expected Behavior**

The session should be maintained after opening new tabs in the same browser.

**Steps to Reproduce the Bug**

1. Go to http://pwa-gh-review-483-universal-b2c.azurewebsites.net/home
2. Login into PWA
3. Open new tab and copy http://pwa-gh-review-483-universal-b2c.azurewebsites.net/home
4. Opening a specific product or page in a new tab will have the same behavior

**Environment Details**

- Desktop: \*

  - Browser: Chrome
  - Project Code Version: Release 0.26

**Comment by dhhyi** [comment]
relates to #manfredsteyer/angular-oauth2-oidc/issues/418
