### ISSUE TITLE
Side Panel Navigation Parameters of Static Content Page Component not used by PWA

### ISSUE THREAD

**Issue by philippsauer** [intershop/intershop-pwa#545]
**Is your feature request related to a problem? If yes, please describe it.**

The configuration parameters for the side panel navigation of 'Static Content Page Component' are not being used by PWA component 'CMSStaticPageComponent'

![image](https://user-images.githubusercontent.com/6233211/107522014-833c0980-6bb3-11eb-97d6-4b3dbba529d8.png)

**Describe the desired solution.**

CMSStaticPageComponent is rendering navigation menu as configured via CMS component 'Static Content Page Component'

**Comment by shauke** [comment]
Initially the CMS REST API did not provide the information to construct the page hierarchy for the static content pages navigation. But with the now available `/cms/pagetree/{pagesKey}` REST resource (https://support.intershop.com/kb/index.php/Display/2956B7#193cfc9be3b995831c6af2fea6650e60) it would be possible to implement this navigation. With this the configuration parameters for the Static Content Page Component would become meaningful again.
