### ISSUE TITLE
Circular dependency when trying to import shared components into shell module (SharedModule <-> ShellModule).

### ISSUE THREAD

**Issue by ismail-codinglab** [intershop/intershop-pwa#551]
I want to use `ish-content-include` to make it possible for the client to edit the header navigation menu items. However to use `ish-content-include` I have to import `sharedModule` into `shellModule`. ShellModule already is being imported by sharedModule, so when i import sharedModule they will depend on eachother creating a circular dependency and giving the error `Maximum call stack exceeded`.

How can I solve this issue?

![image](https://user-images.githubusercontent.com/48755937/108069188-5aa88980-7063-11eb-80f7-e2aac239d515.png)
![image](https://user-images.githubusercontent.com/48755937/108069333-8b88be80-7063-11eb-84db-7fcb72f0f5dd.png)
![image](https://user-images.githubusercontent.com/48755937/108069653-e6221a80-7063-11eb-91b5-90777af93ae0.png)

Note: This will be used as reference and discussed tomorrow with the internal intershop team

**Comment by shauke** [comment]
The linked PR #496 provides a solution to the described problem by providing a lazy loading content include component that can be used within the ShellModule and through that in the header or footer.

You could already cherry pick the relevant changes (everything except the `footer.component.html` example changes) into your project and reference content includes like this `<ish-lazy-content-include includeId="include.general.01.pagelet2-Include"></ish-lazy-content-include>`.

The PR itself is currently still a draft, since we intend to extend our lazy loading generation functionality so that this component could also be generated. The actual functionality will presumably stay pretty much the way it already is.

**Comment by ismail-codinglab** [comment]
Is this a temporary workaround or will this be a new standard?

If you just removed `shellModule` from the imports of `sharedModule` you wouldn't have to implement this.
I tried to remove the shell module from sharedmodule imports and it complains about `ishServerHtml` and `[form]` these are minor changes, i'd say move `ishServerHtml` and import `reactiveForms` to solve these two problems and no longer require `shellModule`.
Problem solved. No workaround needed.

**Comment by dhhyi** [comment]
> If you just removed `shellModule` from the imports of `sharedModule` you wouldn't have to implement this.
> I tried to remove the shell module from sharedmodule imports and it complains about `ishServerHtml` and `[form]` these are minor changes, i'd say move `ishServerHtml` and import `reactiveForms` to solve these two problems and no longer require `shellModule`.
> Problem solved. No workaround needed.

Really? Can you propose a pull request, so we can have a look at it? (also our CI will run and prove you're right)
That would be great 🥰

**Comment by ismail-codinglab** [comment]
It sounds to me like this issue lives for quite some time, have you guys tried something like this? Some more info would be nice

**Comment by dhhyi** [comment]
> It sounds to me like this issue lives for quite some time, have you guys tried something like this?

I was sincere before. Please provide a working example showcasing what you did.
Our CI does some thorough checks if anything can be built for production use and it would be great to include it, if everything works. I'm happy to help if it is just small issues that are missing.

What you are talking about might be a major design flaw we haven't thought about for a long time.
Still, I have some doubts and I wanna see a running (and building) example, please 🙂

**Comment by ismail-codinglab** [comment]
I have taken a good look at it and tried to de-couple `shellModule` from `sharedModule`.
However as i kept decoupling i found out there's a decision being made a while ago which makes this quite a big investment to decouple.

The `shellModule` in my opinion should not be treated as a sharedModule, it should not be a "foundation" for another module. It should be a dead-end for header/footer/whatever. But on a business perspective this isn't feasible.

so we are going with the provided route of something like https://github.com/intershop/intershop-pwa/pull/496.

Thank you for your time and for the quick replies!

**Comment by adrianResler** [comment]
Btw. @shauke do you think that like in #496 would be also a way to go for other `shared` components that we would need to use in `shell`? For example I would need to use `ProductQuantityComponent` in `MiniBasket` that is part of `shellModules` in order to change `lineItem` quantity from the `MiniBasket` overlay level

**Comment by dhhyi** [comment]
Hi @adrianResler,

> For example I would need to use `ProductQuantityComponent` in `MiniBasket` that is part of `shellModules` in order to change `lineItem` quantity from the `MiniBasket` overlay level

Yes, if this PR is merged, it should be possible to do this for any component in the shared module by calling the `lazy-component` schematic. With your example:
```
ng g lazy-component src/app/shared/components/product/product-quantity/product-quantity.component.ts
```
For projects this is a good approach and nothing really speaks against it. By adding lazy component wrappers to the shell the initial bundle doesn't grow as significantly as moving components to the shell module would do. But if this is overused, the code can become quite unreadable.

For the PWA itself I'd rather propose a refactoring and lazy-fy the line item list for the mini-basket in #528 like you just inspired me to do:

https://github.com/intershop/intershop-pwa/blob/e2f1574d5a1a951106b8673d1461b1937ab38174/src/app/shell/header/mini-basket/mini-basket.component.html#L18-L20

That way also the `ish-product-image` component can be moved to the shared module so the initial bundle gets smaller.

**Comment by adrianResler** [comment]
@dhhyi thank you for the answer and efforts! 👍  🚀
