### ISSUE TITLE
Generated compodoc documentation no longer working - is it still needed?

### ISSUE THREAD

**Issue by shauke** [intershop/intershop-pwa#589]
**Actual Behavior**

The generated [compodoc](https://compodoc.app/) is no longer providing the expected documentation for the projects artifacts (components, routing, modules, etc.). 

![image](https://user-images.githubusercontent.com/50741106/109534524-b5a69b80-7abb-11eb-9f47-e2b851c20742.png)

Only the projects Markdown documentation is included for some files.

To generate and test the compodoc documentation run
```
npm run compodoc:serve
```

**Discussion**

We are currently trying to decide whether we should invest time into fixing the compodoc integration or if we should just remove it from this project if nobody is/was using it. The non existing feedback regarding this broken functionality since several releases suggests that nobody is missing this documentation. 😉 

**Voting**
👍 = Keep compodoc and fix it
👎 = Remove compodoc
😕 = I don't care

**Comment by asiebenwirth-ish** [comment]
For the second time already customers asked for an API documentation of the available components, modules etc. So I think this is an important part to get to know the app and learn to work with it knowing all it's capabilities.

**Comment by dhhyi** [comment]
@asiebenwirth-ish I think the modules you will most likely see most when working with the PWA are documented [here](https://github.com/intershop/intershop-pwa/blob/develop/docs/concepts/project-structure.md#modules) and for an overview of reusable components, something like [storybook](https://storybook.js.org/) is more suitable in my opinion. 😉  Have a look at this closed PR: #144

**Comment by jometzner** [comment]
The current status of our documentation can be found here: https://pwa-gh-review-reports.azurewebsites.net/docs/compodoc/index.html

**Comment by fmalcher** [comment]
Do you have any idea why compodoc is broken? Is this a regression thing at compodoc or is it the structure of the Intershop PWA which makes them incompatible?

**Comment by shauke** [comment]
No we have currently no idea why it is no longer working. We have not analyzed this any further yet. We wanted to know if it is even worth to investigate or if nobody is interested in this documentation anyways. If there would be enough interest in a working compodoc documentation we would start to search for the problem. 😉
