### ISSUE TITLE
PWA can't handle "(someval)" in the URL

### ISSUE THREAD

**Issue by 127001** [intershop/intershop-pwa#610]
When the URL contains (someval), the PWA 'crashes' and after the timeout results in a 500 error. In case of the demo website, you'll get the nginx error page.

As far as I can tell, the PWA doesn't create any URL's with the (someval), but that doesn't mean the site should crash. 
In our situation, we have some redirects in place from the old to the new site and those do have this in the URL. (or at least Google thinks so).

**Comment by dhhyi** [comment]
relates to #angular/angular/issues/10280

using fix in [comment](https://github.com/angular/angular/issues/10280#issuecomment-309129784).
Please thumbs-up this comment for #karma 😉

**Comment by dhhyi** [comment]
oh, nevermind. issue is already locked...
