### ISSUE TITLE
Basket lock when multiple requests are send

### ISSUE THREAD

**Issue by ivobrands** [intershop/intershop-pwa#619]
**Is your feature request related to a problem? If yes, please describe it.**

Sometimes when a lot of basket requests are send towards the Intershop Back-end, we get a Basket lock in return. see the logs below: 

```
* Incoming request:
> DELETE /COOP-2240-Site/-/baskets/DrqsEiEbd6EAAAF4BuFxMzUi/items/BBOsEiEbr5sAAAF4ruFxMzUi
* Headers:
> accept: application/vnd.intershop.basket.v1+json
> accept-encoding: gzip, deflate, br
> accept-language: nl-nl
> authentication-token: ****
> connection: close
> content-type: application/vnd.intershop.basket.v1+json
> host: gwmap-prd.coop.nl
> user-agent: Coop/454 CFNetwork/1220.1 Darwin/20.3.0
> x-amzn-apigateway-api-id: **
> x-amzn-trace-id: ****
> x-client-ip: ***
> x-forwarded-for: ****
> x-forwarded-port: 443
> x-forwarded-proto: https
* Content (Type=application/vnd.intershop.basket.v1+json):
>
```
### response
```
[2021-03-15 09:10:42.517 UTC+0000] DEBUG ip-172-18-33-27.eu-west-1.compute.internal ES1 appserver0 [COOP-2240-Site]      com.intershop.component.rest.internal.logging.RestLoggingFilter [] [Unknown] [d3CsEiEbGZ0AAAF4LdBxMzUm] [r3IBAGBPJI8BAAB_-0-00] "http-bio-10104-exec-61"
------------------------------------------------------
* Outgoing response:
* (request was: DELETE /COOP-2240-Site/-/baskets/DrqsEiEbd6EAAAF4BuFxMzUi/items/BBOsEiEbr5sAAAF4ruFxMzUi )
* HTTP Status:
< 423 - Locked
* Headers:
> Content-Type: application/vnd.intershop.basket.v1+json
> authentication-token: ********
* Content (Type=application/vnd.intershop.basket.v1+json):
< <entityType=com.intershop.sellside.rest.common.v1.capi.resourceobject.feedback.FeedbackCtnrRO>
```

**Describe the desired solution.**

We would like some kind of functionality to prevent these errors. We were thinking about some queue that hold back multiple calls to the same url or same base url for example baskets/*.

**Describe alternatives you've considered.**

No alternatives yet.

**Comment by svsaller** [comment]
Could you please also provide the returned error code, as the HTTP status code 423 can have different reasons for this request.

**Comment by ivobrands** [comment]
Since friday there are 4000 baskets on hold because of this problem. Other have transaction locks which resolve in short amount of time but still happen.

**Comment by svsaller** [comment]
To narrow down the problem we need the returned error code from the response body. In this case it should be either "basket.locked_for_order_creation.error" or "request.object_locking_failed.error".
In general, this problem seems to relate more to the ICM REST API than to the PWA. Therefore, I recommend contacting the appropriate support at Intershop as soon as possible to get help with this issue.

**Comment by ivobrands** [comment]
Yes, those to are both coming back to us. I'll contact the ICM REST API team. Thanks for your help.
