### ISSUE TITLE
Theme-dependent not found images

### ISSUE THREAD

**Issue by dhhyi** [intershop/intershop-pwa#625]
**Is your feature request related to a problem? If yes, please describe it.**

Currently the image-not-found image (https://github.com/intershop/intershop-pwa/blob/develop/src/assets/img/not_available.png) is hard-coded in `ish-product-image`:
https://github.com/intershop/intershop-pwa/blob/dca53858266cac33ff956aa52562018d66db5be1/src/app/shared/components/product/product-image/product-image.component.html#L15

This makes it hard to set the image depending on the theme with the PWA's multi-theme support.

**Describe the desired solution.**

- Image source should be set in theme SCSS.
- It should be possible to supply SVG images and have them automatically scale to their surrounding containers.
- **BONUS** The text "NO IMAGE AVAILABLE" should be managed in a translation key and painted on top of the image when rendering, so it can be displayed in the current language.

**Describe alternatives you've considered.**

**Provide additional context.**

Additional images that are statically referenced:

![image](https://user-images.githubusercontent.com/23452927/111875083-34467880-8998-11eb-93ae-d02ab2f063fe.png)

**Comment by andreassteinmann** [comment]
It would also be possible to replace the image using pure CSS styling (a circle with a crossing line) and to add the localized text below it. So you have no image at all and there would be no problem with any theme based image reference.
