### ISSUE TITLE
[nginx] docker build failing for nginx/nginx-prometheus-exporter

### ISSUE THREAD

**Issue by shauke** [intershop/intershop-pwa#632]
**Actual Behavior**

Running `docker build -t nginx nginx` currently results in an error for the `nginx/nginx-prometheus-exporter` step.
```
 > [stage-2 4/6] COPY --from=nginx/nginx-prometheus-exporter /usr/bin/exporter /nginx-prometheus-exporter:
------
failed to compute cache key: "/usr/bin/exporter" not found: not found
```
![image](https://user-images.githubusercontent.com/50741106/112161338-571c9b00-8beb-11eb-9486-1454d7a2f5d8.png)

**Investigation Notes**
The problem occurs with the latest version (0.9.0) of https://hub.docker.com/r/nginx/nginx-prometheus-exporter/tags?page=1&ordering=last_updated that was just recently released.

With a pined version `nginx/nginx-prometheus-exporter:0.8.0` this problem does not occur.

**Quick Fix**
Change the [according line](https://github.com/intershop/intershop-pwa/blob/develop/nginx/Dockerfile#L23) in `nginx/Dockerfile` from
```
COPY --from=nginx/nginx-prometheus-exporter /usr/bin/exporter /nginx-prometheus-exporter
```
to
```
COPY --from=nginx/nginx-prometheus-exporter:0.8.0 /usr/bin/exporter /nginx-prometheus-exporter
```

**Environment Details**

- Docker version 20.10.5, build 55c4c88

**Comment by jometzner** [comment]
Using `latest` as tag of base image can result in such failures.

**Comment by shauke** [comment]
**Reason for Build Failure**
The entrypoint for the nginx/nginx-prometheus-exporter was changed from `ENTRYPOINT [ "/usr/bin/exporter" ]` to `ENTRYPOINT [ "/usr/bin/nginx-prometheus-exporter" ]` so our `/nginx/Dockerfile` needs to be adapted as well to build again.
https://github.com/nginxinc/nginx-prometheus-exporter/pull/164/files#diff-5aecd73bbcb9b7410938673269f0d4e676dd18509277b0ff2f2787c9d3e22604R17

0.8.0
![image](https://user-images.githubusercontent.com/50741106/112190020-e5e9e180-8c04-11eb-8ea6-bc45353bae84.png)

0.9.0
![image](https://user-images.githubusercontent.com/50741106/112190153-06b23700-8c05-11eb-8013-b4a174eee641.png)
