### ISSUE TITLE
Navigating during SSO Registration should not be possible

### ISSUE THREAD

**Issue by MaxKless** [intershop/intershop-pwa#640]
When completing an account registration during the SSO process, the user can click on any header buttons (sign in, categories etc) and implicitly abort the SSO process, causing some illegal states and disrupting the sign in process.

**Expected Behavior**

Either navigating with an incompleted registration form should cancel the registration (like the cancel button does) or the navigation should not be possible (like it is during checkout).

**Steps to Reproduce the Bug**

- Start SSO with Auth0
- Create new customer
- On the "Complete your Registration" page, click somewhere else
- Try signing in again

**Comment by dhhyi** [comment]
@MaxKless As the PWA is using the `/loading` route while SSO is logging in, this should be doable by attaching a [`CanDeactivate`](https://angular.io/api/router/CanDeactivate) to this route 🤔
