### ISSUE TITLE
bug: mini cart opens if the user navigates from checkout to the home page

### ISSUE THREAD

**Issue by SGrueber** [intershop/intershop-pwa#668]
**Actual Behavior**
The mini cart opens if the user navigates from checkout to the home page and there are items in cart.

**Expected Behavior**
 The mini cart is shown but it doesn't open.

**Steps to Reproduce the Bug**

1. Login and add some products to cart
2. Go to cart page and start checkout
3. Navigate to the home page by clicking the logo
4. => mini basket is shown and opens, although no item has been added to cart

**Comment by dhhyi** [comment]
Issue is not yet solved!

*Steps*:
- log in for convenience
- add product to cart (mini cart opens 👍)
- go to cart
- start checkout
- click on product link leaving the checkout

*Expected*
- no mini cart popup

*Actual*
- mini cart pops open
