### ISSUE TITLE
Cant open pwa on localhost in internet explorer

### ISSUE THREAD

**Issue by iznogood112** [intershop/intershop-pwa#689]
**Actual Behavior**

The PWA doesnt work on localhost in internet explorer (windows 10). It keeps showing "Intershop Progressive Web App is loading ..." and has some console errors. 

**Expected Behavior**

I do understand IE isnt supported completly anymore, but it does work a lot better on the test and production environments.
Would be great if it works the same on localhost.

**Steps to Reproduce the Bug**

1. clone the PWA github repo
2. checkout tag 0.28.0
3. run npm i
4. run ng serve
5. open pwa on windows 10 in Internet explorer.

**Environment Details**

- Desktop: 

  - Windows 10
  - IE (Microsoft Windows version 20H2)
  - 0.28.0

**Additional Context, like Screenshots, Log File Snippets etc.**
![image](https://user-images.githubusercontent.com/13200260/117636642-4e732a80-b181-11eb-87cf-80c4eef72ce5.png)

**Comment by jometzner** [comment]
Could be necessary to include more polyfills for your IE version... 

Which IE version are you referring to? I see you refer to a Windows Version, but I'm not aware of that version. Would you mind to include that?

**Comment by iznogood112** [comment]
I tried to look up a IE version but it gives me the windows version when i open "about internet explorer"

![image](https://user-images.githubusercontent.com/13200260/117641692-bf691100-b186-11eb-977b-fb62ad45f67b.png)

**Comment by iznogood112** [comment]
Internet Explorer 11 when i open whatsmybrowser.org

**Comment by jometzner** [comment]
Thanks @iznogood112 for that clarification. I know from other customer project that basic support can be enabled through `.browserslistrc` and additional polyfils. But I cannot tell you the steps you need to take.

One idea I had was to execute the [Angular tour of heroes](https://angular.io/docs) try to get this thing up and running in your IE 11. Basically strip down the app and find out what is missing.

**Comment by jometzner** [comment]
BTW I just learned that IE support is going to be removed with Angular 13. It's deprecated with Angular 12
