### ISSUE TITLE
[QUESTION] SEO locales

### ISSUE THREAD

**Issue by nickyhaze** [intershop/intershop-pwa#69]
I'm currently using the "seo.title.home" in the app-routing-module.ts. 

It's always showing me the "en_US" translation as my title. The weird thing is that I expect to see another translated title here ("nl_NL") since I'm also seeing my other translations perfectly fine in my components while using the translate pipe.

Am I forgetting to set a default language somewhere? Or are the seo related things always looking at "en_US"?

I have defined my own language "nl_NL" inside all my environments as the first locale.

Thank you in advance.

**Comment by Sebastian-Haehnlein** [comment]
we can reproduce this bug, i will provide a pullrequest asap
