### ISSUE TITLE
Product stock alert missing

### ISSUE THREAD

**Issue by Franck-clever** [intershop/intershop-pwa#693]
**Is your feature request related to a problem? If yes, please describe it.**

PWA not provide the stock product alert . 

**Describe the desired solution.**

This is a feature present on the classic version. When a product is out of stock a button on product detail is displayed.
The customer can subscribe to be alerted when product  is replenished

**Describe alternatives you've considered.**

**Provide additional context.**
Is there something on PWA roadmap, because we need this for our project.

**Comment by rkarl-ish** [comment]
Thank you for yorr request. We are going to consider this feature for future releases however currently we do not consider this as high priority.

**Comment by Franck-clever** [comment]
Hi Robert,

Thank you for your answer.
I understand that is not high priority on your side, but it's a high level priority on our client side. This feature is a really business point as service on the relation with their customer.
