### ISSUE TITLE
Direct product adding on cart missing

### ISSUE THREAD

**Issue by Franck-clever** [intershop/intershop-pwa#694]
**Is your feature request related to a problem? If yes, please describe it.**

On the PWA version the feature that allows customer to add directly a product on cart is missing

**Describe the desired solution.**

This is a feature present on the classic version. On the cart, a section allows customer to fill product sku and quantity to add one product at his cart.
![missing_direct_adding](https://user-images.githubusercontent.com/83394914/117857529-2a047480-b28d-11eb-9590-e672d1c34ca1.png)

**Describe alternatives you've considered.**

An alternative is passing by the quick order feature.

**Provide additional context.**
Is there something on PWA roadmap, because we need this for our project.

**Comment by rkarl-ish** [comment]
Thank you for your request. We are considering this enhancement for upcoming releases. You  can also have a look at the quick order feature and see if it can be integrated easily within your project.

**Comment by Franck-clever** [comment]
Hi Robert,

Thank you for your answer. Yes, the quickorder is asked by our client and we'll use it.
But he wants also this feature to add one product directly from the cart.
Have you an idea of the delay to obtain it ?
