### ISSUE TITLE
Customer order number on delivery step missing

### ISSUE THREAD

**Issue by Franck-clever** [intershop/intershop-pwa#697]
**Is your feature request related to a problem? If yes, please describe it.**

On the delivery step of funnel the field to fill the order number for customer is missing.

**Describe the desired solution.**

Is it possible to have on PWA version the same feature that is present on classic version ?
![missing_ordernum_customer](https://user-images.githubusercontent.com/83394914/117999388-16b4e000-b345-11eb-945f-1c633dd92e22.png)

**Describe alternatives you've considered.**

**Provide additional context.**
It's feature needed on our project with the omnichannel context.

**Comment by rkarl-ish** [comment]
Thank you for your request. We are going to consider this feature as an enhancement in one of the upcoming releases.

**Comment by Franck-clever** [comment]
Hi Robert,

Great !! Have you an idea of the delay to obtain it ?
