### ISSUE TITLE
Desired delivery date missing

### ISSUE THREAD

**Issue by Franck-clever** [intershop/intershop-pwa#698]
**Is your feature request related to a problem? If yes, please describe it.**

On PWA, on shipping step of funnel,  the field with the calendar that allows customer to fill his required shipping date are missing

**Describe the desired solution.**

Is it on your roadmap to have on PWA version the same feature as on classic version ?

![calendar_delivery_step](https://user-images.githubusercontent.com/83394914/118001643-38af6200-b347-11eb-925b-efba2669fc73.jpg)

**Describe alternatives you've considered.**

**Provide additional context.**

This feature is needed on our project

**Comment by rkarl-ish** [comment]
Would you need the desired delivery date for the whole basket or per item? The first would be much less effort, the second would require multiple bucket handling which is not yet supported in PWA.

**Comment by Franck-clever** [comment]
Hi Robert,

For this request is less urgent because we have to check some details with the client.
I'll back to you with more information.

**Comment by SGrueber** [comment]
IAD: https://www.figma.com/file/VpP4lX1CUdIlzKsnOYcCTK/PWA-Desired-Delivery-Date?node-id=0%3A1

**Comment by SGrueber** [comment]
As long as we cannot handle multiple buckets only a desired delivery date for the whole order can be provided. There should be a feature toggle to switch the functionality on/off.

**Comment by Franck-clever** [comment]
Hi Robert,

To answer to you, we'd need the desired delivery date for the whole basket.

Best regards,

Franck

**Comment by Franck-clever** [comment]
https://www.figma.com/file/VpP4lX1CUdIlzKsnOYcCTK/PWA-Desired-Delivery-Date?node-id=0%3A1 it will be part of a next release ?

Best regards

**Comment by SGrueber** [comment]
We are currently working on it, but we haven't planned it for the next release. So most probably it won't be part of the next release.

**Comment by Franck-clever** [comment]
Hi Max,

This ticket is closed because this feature will be present in the next release ?
Could you tell me in which release we'll have the feature ?

Regards,

Franck

**Comment by MaxKless** [comment]
This is closed because #1056 introduced this feature and it will be included in release 2.2. 
Beware that currently, the desired delivery date is set as a custom attribute on the basket. This will change with a future ICM release.
