### ISSUE TITLE
Issue on retail set with variant product

### ISSUE THREAD

**Issue by Franck-clever** [intershop/intershop-pwa#723]
It seems there's a regression on retail set behavior

**Actual Behavior**

When a variant product is added to a retail set, the axes of variation don't appear on the line of the variation product in the retail set. Instead there is a link "Choose another variation". This link redirect on the detail product of the variant master product.

**Expected Behavior**

When a variant product is added to a retail set, the axes of variation appear on the line of the variation product in the retail set. So it's possible to change the variation directly from the retail set product.

**Steps to Reproduce the Bug**

1. Go to BO
2. Choose a retail set product
3. On variation tab of the product add a variation product
4. On front, go to the detail product of the retail set. The variation product is visible with only a link "choose another variation" instead to have the axes attributes of variation

**Environment Details**

- Desktop: \*

  - OS: Windows
  - Browser : chrome and Firefox

- Smartphone: \*
  No tested on smartphone

**Additional Context, like Screenshots, Log File Snippets etc.**

**Comment by SGrueber** [comment]
The behavior of the variation handling is customizable with the help of the feature toggle 'advancedVariationHandling'. Per default, it is on for b2b applications and off for b2c applications. 
If this feature toggle is off only the default variation product is shown in product list, the variation attribute can be changed there as well as in the cart.
If the feature toggle is on all variation products are shown in the product lists as independent products, changing the variation is not possible.
Maybe switching off the feature toggle will lead t the desired behavior. Can you check it, pls?

Regards, Silke

**Comment by Franck-clever** [comment]
Hi Silke,

Thanks for your answer.
Could you tell me where this configuration has to be done in ICM ? Or is it a configuration into code ?

Regards,

Franck

**Comment by SGrueber** [comment]
Hi Franck,

this configuration can be done in the PWA, in the environment.ts file.

Regards, Silke

**Comment by Franck-clever** [comment]
Thank you Silke.

Are you ok to leave this ticket open until we do the modification to see if it's ok ?

Regards, Franck

**Comment by SGrueber** [comment]
Yes. of course, 
I am not sure, this will solve your problem, I just want to exclude it can be done by this configuration change.

**Comment by Franck-clever** [comment]
Thanks Silke,

I'll try to do as fast as possible, with our technical team. 

Franck

**Comment by Franck-clever** [comment]
Hi Silke,

My point was something Leo show to us. That a retail set can have a variant product.
I join a capture of what Leo did.
Can you explain to me how do that with Intershop configuration

Best regards
![retailSetwithVariantProduct](https://user-images.githubusercontent.com/83394914/126457690-2624435c-4952-4be8-83a5-4f86cff38325.png)

**Comment by SGrueber** [comment]
Hey Franck,

if you switch off the feature toggle 'advancedVariationHandling' in your environment.ts file the product detail page of a retail set with an variation product looks like the picture below. This is what you want, isn't it?

Best regards

![image](https://user-images.githubusercontent.com/57660644/126973826-cca2e10c-0a62-4834-a939-046c546fc243.png)

**Comment by Franck-clever** [comment]
Hi Silke,

Yes it's exactly that !!
Thank you very much

I close this ticket

Best regards

Franck
