### ISSUE TITLE
GDPR missing on PWA version

### ISSUE THREAD

**Issue by Franck-clever** [intershop/intershop-pwa#725]
**Is your feature request related to a problem? If yes, please describe it.**

On PWA version into my account section there aren't features for customer on his settings to ask about data or deleting his account.

**Describe the desired solution.**

Is it possible to have the same feature on PWA that is present on responsive version  ?
Maybe is something to activate on PWA BO, or properties file, but I didn't find where
![My-Account-Intershop-GDPR-PWA](https://user-images.githubusercontent.com/83394914/121917243-3ae55180-cd35-11eb-86af-6eda4e5e2d1a.png)
![My-Account-Intershop-GDPR-versionResponsive](https://user-images.githubusercontent.com/83394914/121917256-3d47ab80-cd35-11eb-8552-80b92691fe6f.png)

**Describe alternatives you've considered.**

**Provide additional context.**

join a capture of PWA version and responsive version.

**Comment by rkarl-ish** [comment]
Hi Franck,
this feature is currently not supported for PWA. However customers can request their personal data or deletion of their personal data via contact us form. There are options for both retrieval and deletion of personal data available in the the subject dropdown of the form. Based on this email a customer service representative can trigger the process from the backoffice and the customer is informed via email For details see https://support.intershop.com/kb/index.php/Display/28A764

**Comment by Franck-clever** [comment]
Hi Robert,

Thank you for your answer.
In our context project, the contact form will be provided by a CRM and not by Intershop. So I'll see how we could manage this topic with the CRM partner.
