### ISSUE TITLE
Storefinder search button leads to error page 

### ISSUE THREAD

**Issue by M-Behr** [intershop/intershop-pwa#729]
**Actual Behavior**
"Search Now" leads to "Page not found" error. The reason is that the Storefinder is not implemented yet.

**Expected Behavior**
Hide "Search Now" link until Storefinder feature is implemented. Alternatively, we could also adjust the content or hide the whole info box.

**Steps to Reproduce the Bug**

1. Go to 'Helpdesk'
2. Click on 'Search Now'

**Environment Details**

- Public Demo Server Version 0.31

**Additional Context, like Screenshots, Log File Snippets etc.**
![storefinder_search](https://user-images.githubusercontent.com/66066967/122044506-e09fcb80-cddc-11eb-8cb2-fb7cd881e9d4.png)

[AB#64652](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/64652)

**Comment by shauke** [comment]
The Link will be removed in ICM 7.10.32.3-LTS and 7.10.34.0.
