### ISSUE TITLE
Add retail set from quickorder not same behavior as add from products list

### ISSUE THREAD

**Issue by Franck-clever** [intershop/intershop-pwa#731]
**Actual Behavior**

It's possible to add a retail set from product list, each product into the retail set becomes a product line of the cart.
But it's not possible to add a retail set from the quickorder form or from the quickorder field on cart. In these cases, an error message is displayed to inform that product can't be add for the whole.

**Expected Behavior**

Expected behavior would be that adding retail set is the same from product list or quickorder (both quickorder)

**Steps to Reproduce the Bug**

_On responsive and PWA version_
1. search a retail set product
2. add it to the cart from the product list 
3. Success. Each product of the retail set has been added to the cart

 _On responsive and PWA version_
1. On the quickorder fills the field with the retail set product reference and with 1 for quantity
2. click on button add to the cart
3. Failed. No product has been added to the cart

 _On responsive  version only ( feature not present on PWA version)_
1.  On the cart into the quickorder field fills the retail set product reference
2. click on button add to the cart 
3. Failed. No product has been added to the cart

**Environment Details**

Tested on responsive and PWA version of Intershop

**Additional Context, like Screenshots, Log File Snippets etc.**

screenshot of message for case 1 and 2

![bug-ajout rapide- produit retail set](https://user-images.githubusercontent.com/83394914/122067786-24ea9600-cdf4-11eb-8e2b-fa09ec168b02.jpg)

**Comment by SGrueber** [comment]
Hi,
I could not reproduce this issue with our demo data. 
Steps to repeat: 
- open public PWA demo - https://intershoppwa-b2b.azurewebsites.net/home
- go to quick order
- add the retail set with id '201807198' (Microsoft Surface Pro Set Burgundy) to cart
- > all 4 retail set items are added to cart

Can you provide steps to repeat with our demo data ?
It seems a REST request responded with an error, can you attach the request data and the error response?

Thank you.

**Comment by Franck-clever** [comment]
Hi,
Thank you for your answer. I tested on your demo and it's also ok for me :-).
Have you the same behavior on responsive version from the quick add on cart ?
Because if there's no issue I'll close this ticket

Best regards

Franck

**Comment by SGrueber** [comment]
Hi,
in the responsive starter store adding a retail set from quick order doesn`t work properly. I could reproduce it.
But here in github only PWA issues are handled, I am sorry.
Please, contact our support department and open an escalation, if you want us to fix it in the responsive starter store.

**Comment by Franck-clever** [comment]
Hi Slike,

My point is on PWA only but I can't test the retail set adding from cart, because this feature is missing on PWA version.

Best regards,

Franck
