### ISSUE TITLE
send cart by email and upload PDF are missing on PWA

### ISSUE THREAD

**Issue by Franck-clever** [intershop/intershop-pwa#733]
**Is your feature request related to a problem? If yes, please describe it.**

We can activate the features to send cart by email and upload the PDF of cart, but this is not visible on front into the cart.

**Describe the desired solution.**

Is it possible to have the same feature that on responsive version ?

**Describe alternatives you've considered.**

no alternative

**Provide additional context.**

**Comment by rkarl-ish** [comment]
Thank you for your feedback. The email cart feature has been removed from the responsive starter store due to data privacy regulations. Therefore it is also not planned for PWA. Print to pdf is considered low priority and currently not planned as well.

**Comment by 5t3v3n-H** [comment]
Will not be implemented in the PWA.
