### ISSUE TITLE
[Bug] DOM Warning on Home Page: duplicate element ID

### ISSUE THREAD

**Issue by dhhyi** [intershop/intershop-pwa#74]
**Actual Behavior**

![image](https://user-images.githubusercontent.com/23452927/71545447-63d02600-298b-11ea-802b-7efecfd2eefc.png)

**Expected Behavior**
 

No duplicate DOM element IDs

**Steps to Reproduce the Bug**

go to https://intershoppwa.azurewebsites.net/home
Open browser console.

**Comment by shauke** [comment]
Closed by #76
