### ISSUE TITLE
Shouldn't canonical and og:url be https in the source code?

### ISSUE THREAD

**Issue by iznogood112** [intershop/intershop-pwa#749]
If you look at the intershop demo site and open the source code directly the canonical and og:url are shown as http://

<link rel="canonical" href="http://intershoppwa-b2b.azurewebsites.net/home">
<meta property="og:url" content="http://intershoppwa-b2b.azurewebsites.net/home">

https://intershoppwa-b2b.azurewebsites.net/home 

we currently using 0.28.0 but i see the same situation on the demo environment linked above.

[AB#64588](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/64588)

**Comment by rkarl-ish** [comment]
Thank you for the feedback. We will have a look.

**Comment by 127001** [comment]
Some additional information as to the impact this issue could have (we are still investigating). 
Most websites require https these days, especially webshops. So in our situation, all http traffic is redirected to https. 

If we take a look at a random product url: https://intershoppwa-b2b.azurewebsites.net/Acer/Acer-ICONIA-W500P-%2B-Keydock-sku10957684-catComputers.897.897_Acer?view=grid and provide it to a seo tester (Screaming Frog), we see that the specified URL is 'non-indexable'. This seems to be directly related to the provided canonical being different to the visited page. The same result, with less information, is shown in Google Search Tools.


|Name                                 |Value                                                                                                                        |
|-------------------------------------|-----------------------------------------------------------------------------------------------------------------------------|
|Address                              |https://intershoppwa-b2b.azurewebsites.net/Acer/Acer-ICONIA-W500P-%2B-Keydock-sku10957684-catComputers.897.897_Acer?view=grid|
|URL Encoded Address                  |https://intershoppwa-b2b.azurewebsites.net/Acer/Acer-ICONIA-W500P-%2B-Keydock-sku10957684-catComputers.897.897_Acer?view=grid|
|Content Type                         |text/html; charset=utf-8                                                                                                     |
|Status Code                          |200                                                                                                                          |
|Status                               |OK                                                                                                                           |
|HTTP Version                         |HTTP/1.1                                                                                                                     |
|Indexability                         |Non-Indexable                                                                                                                |
|Indexability Status                  |Canonicalised                                                                                                                |
|Size                                 |217.1 KB                                                                                                                     |
|Title 1                              |Acer ICONIA W500P + Keydock - Acer &#124; Intershop PWA                                                                           |
|Title 1 Length                       |50                                                                                                                           |
|Meta Description 1                   |Acer ICONIA W500P + Keydock - W500P - AMD Fusion C-60 1.0GHz, 2GB DDR3, 32GB SSD, 10.1” TFT LCD                              |
|Meta Description 1 Length            |95                                                                                                                           |
|Meta Description 1 Pixel Width       |690                                                                                                                          |
|H1-1                                 |Acer ICONIA W500P + Keydock                                                                                                  |
|H1-1 Length                          |27                                                                                                                           |
|Meta Robots 1                        |index, follow                                                                                                                |
|Canonical Link Element 1             |http://intershoppwa-b2b.azurewebsites.net/Acer/Acer-ICONIA-W500P-+-Keydock-sku10957684-catComputers.897.897_Acer             |
|Canonical Link Element 1 Indexability|                                                                                                                             |
|Word Count                           |608                                                                                                                          |
|Text Ratio                           |2.91                                                                                                                         |
|Crawl Depth                          |0                                                                                                                            |
|Link Score                           |                                                                                                                             |
|Inlinks                              |2                                                                                                                            |
|Unique Inlinks                       |1                                                                                                                            |
|% of Total                           |1.96                                                                                                                         |
|Outlinks                             |130                                                                                                                          |
|Unique Outlinks                      |119                                                                                                                          |
|External Outlinks                    |6                                                                                                                            |
|Unique External Outlinks             |5                                                                                                                            |
|Hash                                 |8eea80ed010fa2622c92bbf5fe98f920                                                                                             |
|Response Time                        |0.76                                                                                                                         |
|Last Modified                        |                                                                                                                             |
|Response Header: Cache-Control       |max-age=0, no-cache                                                                                                          |
|Response Header: Content-Encoding    |gzip                                                                                                                         |
|Response Header: Date                |Fri, 02 Jul 2021 07:05:00 GMT                                                                                                |
|Response Header: Server              |nginx/1.19.7                                                                                                                 |
|Response Header: Transfer-Encoding   |chunked                                                                                                                      |
|Response Header: Vary                |Accept-Encoding                                                                                                              |
|Response Header: x-cache-status      |MISS                                                                                                                         |
|Response Header: x-icm-channel       |inSPIRED-inTRONICS_Business-Site                                                                                             |
|Response Header: x-icm-default-lang  |default                                                                                                                      |
|Response Header: x-page-speed        |1.13.35.2-0                                                                                                                  |
|Response Header: x-powered-by        |Express                                                                                                                      |
|Response Header: x-ua-device         |desktop                                                                                                                      |


Performing the same test on the http url, provided by the canonical, you will see that the page is indeed index-able. But that is actually the problem for many sites, including the one we are developing:

|Name                                 |Value                                                                                                                        |
|-------------------------------------|-----------------------------------------------------------------------------------------------------------------------------|
|Address                              |http://intershoppwa-b2b.azurewebsites.net/Acer/Acer-ICONIA-W500P-+-Keydock-sku10957684-catComputers.897.897_Acer             |
|URL Encoded Address                  |http://intershoppwa-b2b.azurewebsites.net/Acer/Acer-ICONIA-W500P-+-Keydock-sku10957684-catComputers.897.897_Acer             |
|Content Type                         |text/html; charset=utf-8                                                                                                     |
|Status Code                          |200                                                                                                                          |
|Status                               |OK                                                                                                                           |
|HTTP Version                         |HTTP/1.1                                                                                                                     |
|Indexability                         |Indexable                                                                                                                    |
|Size                                 |217.1 KB                                                                                                                     |
|Title 1                              |Acer ICONIA W500P + Keydock - Acer &#124; Intershop PWA                                                                           |
|Title 1 Length                       |50                                                                                                                           |
|Meta Description 1                   |Acer ICONIA W500P + Keydock - W500P - AMD Fusion C-60 1.0GHz, 2GB DDR3, 32GB SSD, 10.1” TFT LCD                              |
|Meta Description 1 Length            |95                                                                                                                           |
|Meta Description 1 Pixel Width       |690                                                                                                                          |
|H1-1                                 |Acer ICONIA W500P + Keydock                                                                                                  |
|H1-1 Length                          |27                                                                                                                           |
|Meta Robots 1                        |index, follow                                                                                                                |
|Canonical Link Element 1             |http://intershoppwa-b2b.azurewebsites.net/Acer/Acer-ICONIA-W500P-+-Keydock-sku10957684-catComputers.897.897_Acer             |
|Canonical Link Element 1 Indexability|Indexable                                                                                                                    |
|Word Count                           |608                                                                                                                          |
|Text Ratio                           |2.91                                                                                                                         |
|Crawl Depth                          |0                                                                                                                            |
|Link Score                           |                                                                                                                             |
|Inlinks                              |0                                                                                                                            |
|Unique Inlinks                       |0                                                                                                                            |
|% of Total                           |0.0                                                                                                                          |
|Outlinks                             |130                                                                                                                          |
|Unique Outlinks                      |119                                                                                                                          |
|External Outlinks                    |6                                                                                                                            |
|Unique External Outlinks             |5                                                                                                                            |
|Hash                                 |833500f284d6e8e3dd3a906dac05cfaf                                                                                             |
|Response Time                        |0.66                                                                                                                         |
|Last Modified                        |                                                                                                                             |
|Response Header: Cache-Control       |max-age=0, no-cache                                                                                                          |
|Response Header: Content-Encoding    |gzip                                                                                                                         |
|Response Header: Date                |Fri, 02 Jul 2021 07:16:21 GMT                                                                                                |
|Response Header: Server              |nginx/1.19.7                                                                                                                 |
|Response Header: Transfer-Encoding   |chunked                                                                                                                      |
|Response Header: Vary                |Accept-Encoding                                                                                                              |
|Response Header: x-cache-status      |EXPIRED                                                                                                                      |
|Response Header: x-icm-channel       |inSPIRED-inTRONICS_Business-Site                                                                                             |
|Response Header: x-icm-default-lang  |default                                                                                                                      |
|Response Header: x-page-speed        |1.13.35.2-0                                                                                                                  |
|Response Header: x-powered-by        |Express                                                                                                                      |
|Response Header: x-ua-device         |desktop                                                                                                                      |

And finally, to give you an idea on what is happening in Google for our site:

![Screenshot from 2021-07-02 09-19-25](https://user-images.githubusercontent.com/149222/124236832-2c5daf00-db17-11eb-8838-d362ea0a503a.png)

**Comment by shauke** [comment]
The source code that sets the value for the canonical URL looks like this: `this.doc.URL.replace(/[;?].*/g, '')`.
It uses the current documents URL and with that the current protocol. In an SSR context it is important how the PWA is deployed so that this protocol already fits for the initial request. By default the PWA is deployed with `http` so the canonical link uses this protocol. If the PWA would be deployed with `SSL=1` the `https` protocol would be used by default and the canonical URL would use this as protocol.

For some reason the PWA production deployments are done with `http` and the `https` redirect is done afterwards. We need to investigate further how this can be resolved.

**Comment by shauke** [comment]
Production PWAs should always be run in a secure context but the PWA SSR container itself is usually not run in a secure context in production. The SSL certification is handled outside the PWAs context. This makes it hard to get the correct protocol from the PWA SSR context even though it is a secure context to the user. For this reason we always set the canonical link URLs and the 'og:url' to 'https:' to prevent false non indexable canonical links.

**Comment by 127001** [comment]
Thanks for the update. The replace in seo.effects is pretty much the same way how we solved this with a quickfix.

**Comment by shauke** [comment]
Yes after discussing the different options, this one seemed the most effective and without the need for unnecessary overhead. So we went with this fix. ;)
