### ISSUE TITLE
Store locator missing on PWA

### ISSUE THREAD

**Issue by Franck-clever** [intershop/intershop-pwa#754]
**Is your feature request related to a problem? If yes, please describe it.**

On the PWA version I didn't find how to reach the store locator search engine.

**Describe the desired solution.**

Having the search engine for store locator like on classic version of Intershop

**Describe alternatives you've considered.**

no alternatives identified

**Provide additional context.**

**Comment by Franck-clever** [comment]
I close this issue because in fact there's an issue declared here : https://github.com/intershop/intershop-pwa/issues/729

**Comment by rkarl-ish** [comment]
Reopening the issue since the store locator is still missing
