### ISSUE TITLE
`npm run start:local` (serve-ssr) no longer working

### ISSUE THREAD

**Issue by shauke** [intershop/intershop-pwa#758]
**Actual Behavior**

The run script `npm run start:local` that maps to `ng run intershop-pwa:serve-ssr:local` that is supposed to run a development PWA server with Server Side Rendering is no longer working as expected. Instead of rendering any page opening the PWA results in `undefined:7:223720: missing '}'` (the number might vary).

When starting the PWA with `npm run start` or `ng serve` the PWA pages render as expected.

**Expected Behavior**

Normally rendering any PWA page when running `npm run start:local`.

**Steps to Reproduce the Bug**

1. checkout the current `develop` branch
2. `npm install`
3. `npm run start:local`
4. open http://localhost:4200

**Notes**
The problem was introduced with the "deps: update to Angular 12 and Webpack 5" commit https://github.com/intershop/intershop-pwa/commit/c3c80edba22e2a1284ffabe90acef031864f377b.

**Comment by dhhyi** [comment]
Build defaults have changed in Angular 12. By default a production build is now executed. To fix this, `local` must disable some options.
