### ISSUE TITLE
incorrect product label display on product detail page - product context issue?

### ISSUE THREAD

**Issue by shauke** [intershop/intershop-pwa#762]
**Actual Behavior**

If one switches in the product detail view directly from a product with a product label to a product that should not have such a product label (e.g. via switch between recently viewed products) the previously displayed product label sticks and is displayed wrong with a product that should not have it. Switching between products with different product labels works as expected. Only the switch from label to without label works wrong. Maybe this is an issue with the product context?

In addition there is a styling issue with the product labels on the product detail page that needs an additional `z-index` in the `product-list.scss` files definition that should be fixed together with this issue.
```
.product-label {
  position: absolute;
  top: 90px;
  left: -6px;
  z-index: 10;
```
![image](https://user-images.githubusercontent.com/50741106/124090730-66667c80-da55-11eb-890b-49028bfb508d.png)

**Expected Behavior**

The product detail page should always only show the fitting product label.

**Steps to Reproduce the Bug**

1. Go to a product detail page with product label (e.g. Specials > Hot Deals products)
2. Go to a product detail page without label (e.g. Google Home)
3. Switch between the two product detail pages via recently viewed listing

**Comment by dhhyi** [comment]
@shauke can you add an `|| null` here and re-test?:
https://github.com/intershop/intershop-pwa/blob/1fa5e02e19c2bd628d0585266fc7f593e9e633e2/src/app/core/facades/product-context.facade.ts#L230
