### ISSUE TITLE
display product attachments at the product details page

### ISSUE THREAD

**Issue by shauke** [intershop/intershop-pwa#767]
The PWA does currently not support the display of product attachments even though the ICM REST API provides all necessary information now (see https://intershoppwa.azurewebsites.net/INTERSHOP/rest/WFS/inSPIRED-inTRONICS-Site/rest/products/201807231-01).

![image](https://user-images.githubusercontent.com/50741106/124160339-748bbb80-da9c-11eb-94aa-26b8c7e95b80.png)

With the link information a working URL can be constructed that will download the attachment, e.g. 
https://intershoppwa.azurewebsites.net/INTERSHOP/rest/WFS/inSPIRED-inTRONICS-Site/rest;loc=en_US/attachments/inSPIRED%253A%252Fmanuals%252Fsurface-book-user-guide-EN.pdf

With this information product attachment information similar to the Responsive Starter Store should be implemented.
![image](https://user-images.githubusercontent.com/50741106/124160887-05629700-da9d-11eb-839f-38b15d2025ca.png)
https://pwa-ish-demo.test.intershop.com/INTERSHOP/web/WFS/inSPIRED-inTRONICS-Site/en_US/-/USD/ViewProduct-Start?SKU=201807231-01&CategoryName=897_Microsoft&CategoryDomainName=inSPIRED-Computers

[AB#64627](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/64627)

**Comment by M-Behr** [comment]
New IAD/VD:
The UX team would like to replace the icon with a link to make the "Download" action clearer, as well as change the headline so that the content reflects expectations.
![IADVD_PWA_ProductAttachments](https://user-images.githubusercontent.com/66066967/124559292-dbfa9000-de3b-11eb-8ae0-47a82156c907.png)
