### ISSUE TITLE
"RangeError Maximum call stack size exceeded" errors in SSR

### ISSUE THREAD

**Issue by shauke** [intershop/intershop-pwa#783]
**Actual Behavior**

When running the the PWA in server side rendering (SSR) the following errors are logged to the SSR console.

***run with `npm run start`***
```
ERROR RangeError Maximum call stack size exceeded at isObject (D:\DEV_PWA\intershop-pwa\dist\server\main.js:1:5374341)
```

***run with `npm run start:local`***
```
ERROR RangeError Maximum call stack size exceeded at Array.filter (<anonymous>)

1 rules skipped due to selector errors:
  .custom-file-input:lang(en) ~ .custom-file-label -> unmatched pseudo-class :lang
```

**Expected Behavior**

There should not be any errors when running the SSR PWA.

[AB#64808](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/64808)

**Comment by dhhyi** [comment]
@shauke I previously observed, that the `RangeError` is only happening for us if the page contains a `swiper`. Maybe that helps.

**Comment by jometzner** [comment]
That error is indeed quite annoying as it spawns the log stream every 10 seconds. Probably due to liveness/readiness checks

**Comment by jometzner** [comment]
I can confirm that the error is indeed caused by the `swiper` carousel.

**Comment by jometzner** [comment]
Also found these `RangeError` output lines in the beginning of the ssr container log.
```
ERROR RangeError Maximum call stack size exceeded at Array.filter (<anonymous>)
ERROR RangeError Maximum call stack size exceeded at /dist/server/main.js:1:5372475
ERROR RangeError Maximum call stack size exceeded at Array.filter (<anonymous>)
ERROR RangeError Maximum call stack size exceeded at Array.filter (<anonymous>)
ERROR RangeError Maximum call stack size exceeded at Array.filter (<anonymous>)
ERROR RangeError Maximum call stack size exceeded at Array.filter (<anonymous>)
```

**Comment by dhhyi** [comment]
> Also found these `RangeError` output lines in the beginning of the ssr container log.

That could be the healthcheck rendering the home page (which also contains a `swiper`). 🤔

**Comment by shauke** [comment]
The problem seems to be resolve since the latest Swiper dependencies update.
