### ISSUE TITLE
Product compare is slightly to wide for mobile view

### ISSUE THREAD

**Issue by cbratsch** [intershop/intershop-pwa#802]
**Actual Behavior**
Product compare is slightly to wide for mobile view
You can't see all information of a single product

**Expected Behavior**
All information of a single product can be seen in a mobile device. Maybe also a little slice of the compared product

** Precondition **
* Use a mobile device

**Steps to Reproduce the Bug**

1. go to storefront and hover over a product
-> it's better to see with a product, which includes a bit more text (e.g. over Microsoft Surface Book 2)
2. click on the compare icon
3. repeat this for another product
4. click on the "Compare" link in the header
5. See 
![image](https://user-images.githubusercontent.com/57700960/127274082-9efa32f7-d05b-46bb-b0b4-c9a0a8c7ffe3.png)

**Environment Details**

- Smartphone: \*
  - Device: HTC U11 life
  - OS: Android 9
  - Browser Ecosia 4.3.0

[AB#65573](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/65573)

**Comment by MoritzRS** [comment]
I wonder if this is actually a bug. The way the layout works, comparing columns are based on fixed value widths and not relative values to screen size. That means that a column was never intended to be exactly (or less) the width of the view.

You can see this behavoir for wider screens in the images below with different view sizes:

<img src="https://user-images.githubusercontent.com/28864167/135972136-d4dc564f-7e58-4841-a6aa-e0725923aa3b.png" height="500" title="wide"> <img src="https://user-images.githubusercontent.com/28864167/135972204-4ba2c6e5-ebf0-4d95-8362-10ba79bdda82.png" height="500" title="wider">

**Comment by SGrueber** [comment]
We won't fix this issue.
