### ISSUE TITLE
[Bug] Racecondition in quote-request.service

### ISSUE THREAD

**Issue by Sebastian-Haehnlein** [intershop/intershop-pwa#82]
**Actual Behavior**

sometimes there is an error on quote/request-detail-page

**Expected Behavior**
 
 no racecondition

**Steps to Reproduce the Bug**

1. login into b2b
2. go to quote/request detail page ( MY ACCOUNT / QUOTES / QUOTE DETAILS )
3. refresh window (f5)
4. sometimes there is an error "{message: 'not logged in'}"
![Bildschirmfoto von 2020-01-14 15-04-01](https://user-images.githubusercontent.com/50739746/72350653-2683cc00-36df-11ea-8af0-5e9836e445ce.png)

**Environment Details**

*Desktop:   
 - Browser chrome

**Additional Context, like Screenshots, Log File Snippets etc.**

src/app/extensions/quoting/services/quote-request/quote-request.service.ts line 38 - 45 (this.ids$ = ...)

**Comment by MaxKless** [comment]
This was fixed in https://github.com/intershop/intershop-pwa/pull/367
