### ISSUE TITLE
Wrong error message shows up, when user is logged out by time out on cart or checkout pages

### ISSUE THREAD

**Issue by cbratsch** [intershop/intershop-pwa#822]
**Actual Behavior**
Wrong error message shows up, when user is logged out by time out on cart or checkout pages

**Expected Behavior**
The error message should not show up here.

**Steps to Reproduce the Bug**

1. login to the storefront add products to cart or start checkout
2. go to basket and wait for time out of user login
![image](https://user-images.githubusercontent.com/57700960/128337925-474a3706-f23b-4b5f-b81b-a928c93829b6.png)

[AB#65874](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/65874)

**Comment by 5t3v3n-H** [comment]
Solved with Token REAT API rework. #1156
