### ISSUE TITLE
Automatic scroll up to inline error messages

### ISSUE THREAD

**Issue by M-Behr** [intershop/intershop-pwa#848]
**Is your feature request related to a problem? If yes, please describe it.**

I'm always frustrated when "Continue Checkout" is disabled and I don't see the error message at first glance (see screenshot).

Inline messages are displayed below the headline. The checkout button is usually further down on the page (especially in mobile). If a user clicks "Continue Checkout" and an error is displayed, the button is disabled. However, the error is not immediately visible. You have to scroll up first.

**Describe the desired solution.**

If an error message is displayed, scroll automatically to the message.

**Describe alternatives you've considered.**

If an error message is displayed, scroll automatically to top of the page. Inline messages are below page title. They should then also be in the visible area.

**Provide additional context.**
![2021-08-25 09_40_20-Checkout _ Intershop PWA](https://user-images.githubusercontent.com/66066967/130766738-d1bb7a74-dbf5-4f35-9d92-59da4b9358ac.png)

[AB#69214](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/69214)

**Comment by SGrueber** [comment]
Consider to introduce toast messages in the checkout
