### ISSUE TITLE
HTTPS on SSR container is not working anymore

### ISSUE THREAD

**Issue by jometzner** [intershop/intershop-pwa#851]
**Actual Behavior**

```console
docker build ... intershop-pwa_pwa
docker run -d -p 4200:4200 -e TRUST_ICM=true -e SSL=1 --restart always --name yourcontainer intershop-pwa_pwa
```

Starting the ssr container with environment variable SSL=1 does not lead to a functional https://localhost:4200 Instead you receive browser error page telling you `ERR_SSL_PROTOCOL_ERROR`. Trying to access site with http instead of https doesn't solve this. There you just get http error 504 (gateway timeout).

**Expected Behavior**

Running the ssr image with SSL=1 must lead to a site that is capable to serve https.

**Steps to Reproduce the Bug**

1. Build docker image in project root
2. Start docker image as container with SSL=1
3. Open https://localhost:4200 in browser

**Technical investigation**
Multi-theme support distributes requests based on logic implemented in `dist/server.js`. In there we are using express-http-proxy which needs to be configured accordingly. See [package documentation](https://www.npmjs.com/package/express-http-proxy#https)

[AB#69237](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/69237)

**Comment by dhhyi** [comment]
@jometzner @rkarl-ish,

Is this really an issue worth fixing? Usually the PWA deployment contains both nginx and SSR. If used in an actual deployment (i.e. Intershop CaaS), https will be added by the cloud provider by other means.
