### ISSUE TITLE
Approver user shouldn't be able to process his own orders

### ISSUE THREAD

**Issue by Franck-clever** [intershop/intershop-pwa#854]
**Actual Behavior**

A user of customer account with an approver profil can process his own orders if he has a budget limit.

**Expected Behavior**

A user with approver profil and budget limit shouldn't be able to process his own orders. He shouldn't see its into approvals list of orders. The process to accept or reject order should be done by an another user with approver profil.

**Steps to Reproduce the Bug**

1) Create a user with approver profil
2) Give him a budget limit on his  order spend Limit.
3)Log to the site with his account 
4) Make order with an amount that exceeds his budget
5) Place order 
6) Go to his account 
7) Open Approvals menu

As user approver I see my order and I can accept ou reject my own order.

**Environment Details**
no matters

**Additional Context, like Screenshots, Log File Snippets etc.**

[AB#69383](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/69383)

**Comment by rkarl-ish** [comment]
Hi Franck. This behaviour is intended. Imagine a professional buyer who has budget responsibility. Why should this person be forced to find someone else to approve his/her orders. If you want this to behave different in your project, feel free to customize it.
