### ISSUE TITLE
multiple theme support should change system icons (e.g. favicon) too

### ISSUE THREAD

**Issue by shauke** [intershop/intershop-pwa#88]
**Is your feature request related to a problem? If yes, please describe it.**

The current implementation of the multiple theme support (see #49) can change the complete styling off the whole storefront application including the logo images in the header. It basically allows to change everything that can be controlled via CSS.

Unfortunately some logo images that are part of the PWA and its appearance are not configured via CSS and therefore are not yet changeable via the current multiple theme support implementation. In detail these are:
* favicon.ico (see `index.html` in `src` folder)
* PWA icons (see `manifest.webmanifest` in `src` folder)
* Apple icons (see `index.html` in `src` folder)
* `<meta name="theme-color" content="#ff6d00" />`

**Describe the desired solution.**

A solution is required that will change the used/referenced files based on the already available `theme` environment configuration, e.g. `theme: blue`.

**Provide additional context.**

The needed logo files in the fitting blue color (#688dc3) are provided at this ticket.

**Comment by iwiederhold** [comment]
[logo_B2B.zip](https://github.com/intershop/intershop-pwa/files/4086857/logo_B2B.zip)
