### ISSUE TITLE
Wrong Return Urls after payment redirect for non-default languages using nginx multisite configuration

### ISSUE THREAD

**Issue by SGrueber** [intershop/intershop-pwa#912]
Precondition:
PWA with multisite configuration and nginx, e.g. a PWA started with docker-compose

**Actual Behavior**

If the user switches the language and uses a payment method that requires a redirect the return url contains the current locale only as query params, but not as part of the url path

example:
default language: English, url: http://localhost:4200/en/route
changed language: French,  url: http://localhost:4200/fr/route
return url after redirect: http://localhost:4200/en/checkout/review;lang=fr_FR?...

**Expected Behavior**

The path of the return URL reflects the selected language of the user, i.e. it looks like http://localhost:4200/locale/....

example:  http://localhost:4200/fr/checkout/review;lang=fr_FR?...

**Steps to Reproduce the Bug**

1. Open PWA and switch language to French
2. Login, add products to basket and start checkout
3. On checkout payment page select a redirect payment method, e.g ISH credit card 
4. After redirect check the url path, 
-> the default language will be part of it instead of the selected language

**Environment Details**
only valid in a multisite configuration with nginx

- Desktop: \*

  - Browser [e.g. chrome, safari], Version [e.g. 22]
  - Project Code Version

- Smartphone: \*
  - Browser [e.g. stock browser, safari], Version [e.g. 22]
  - Project Code Version

**Additional Context, like Screenshots, Log File Snippets etc.**

![image](https://user-images.githubusercontent.com/57660644/138675357-214a9a8c-7b52-4a6c-8979-dbdaa502a439.png)

[AB#70767](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/70767)

**Comment by rkarl-ish** [comment]
Consider SSO redirects as well.

**Comment by MaxKless** [comment]
Compare [multi-site.service.ts](https://github.com/intershop/intershop-pwa/blob/develop/src/app/core/utils/multi-site/multi-site.service.ts) and consider implementing a shared configuration between nginx and the PWA (for example to have a centrally defined place for `baseHref`s)
