### ISSUE TITLE
User Invitation E-mail refers to incorrect URL so that password update is not possible

### ISSUE THREAD

**Issue by M-Behr** [intershop/intershop-pwa#933]
**Actual Behavior**

The user invitation e-mail refers to an incorrect URL.
For example: https://intershoppwa-b2b.azurewebsites.net/invite;lang=en_US?uid=LQcKCgoE17QAAAF9wplnlFI.&Hash=44c858bb-2e7e-4d4c-92b0-3b3627f05fde
It is not possible to open the password update page. An error page is shown:
<img width="317" alt="2021-11-24 11_00_36-Error" src="https://user-images.githubusercontent.com/66066967/143257561-a1c26213-213f-4cd5-886c-195b26aea786.png">

**Expected Behavior**

The user invitation e-mail refers to the password update page.
For example: https://intershoppwa-b2b.azurewebsites.net/forgotPassword/updatePassword;lang=en_US?uid=LQcKCgoE17QAAAF9wplnlFI.&Hash=44c858bb-2e7e-4d4c-92b0-3b3627f05fde

**Steps to Reproduce the Bug**

1. Login with an account admin
2. Go to 'User Management'
3. Click on 'Add User'
4. Add a new user
5. Open the 'Welcome to inTRONICS Business' e-mail
6. Click on 'New Password' or use the URL

**Environment Details**

- PWA 1.3 - Public Demo Server
- Chrome

[AB#71598](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/71598)

**Comment by SGrueber** [comment]
This problem only occurs if SSR/nginx is used

**Comment by jometzner** [comment]
@kolllor33 Kindly check out the pull request https://github.com/intershop/intershop-pwa/pull/1200

**Comment by kolllor33** [comment]
The pull request looks good to me 👍
