### ISSUE TITLE
Cost center management - Inactive status is not displayed in buyer list

### ISSUE THREAD

**Issue by M-Behr** [intershop/intershop-pwa#958]
**Actual Behavior**

Inactive status is not displayed.

**Expected Behavior**

Please display user as inactive, e. g. Jack Link (inactive) on buyer list and on "Add buyer" page.
See design in user list on user management page.

**Steps to Reproduce the Bug**

1. Go to 'user management'
2. Set user to 'inactive'
3. Go to 'cost center management'
4. Click on 'Oil Corp Headquarter'
5. Add buyer to cost center

**Environment Details**

- Desktop: 

  - Browser: Chrome
  - Project Code Version: PWA 1.4 Public Demo Server

**Additional Context, like Screenshots, Log File Snippets etc.**

<img width="585" alt="cost center_inactive user" src="https://user-images.githubusercontent.com/66066967/145856700-d1436848-8aec-41cc-bb9a-9de3c62bf6f7.png">

<img width="448" alt="cost center_inactive user(2)" src="https://user-images.githubusercontent.com/66066967/145856926-1c7b8022-5d50-43e8-b595-d752733209f0.png">

[AB#72081](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/72081)

**Comment by SGrueber** [comment]
Currently it is not possible to show the active flag in the cost center buyers list, because it is not returned by the cost center REST call. See AB#72203
