### ISSUE TITLE
Cost center management - No approver and comment for system rejected requisitions

### ISSUE THREAD

**Issue by M-Behr** [intershop/intershop-pwa#961]
**Actual Behavior**

The approver and the comment is not visible if requisition is rejected by system.
Rejected by system is not displayed in the requisition list, e. g. Jack Link.

**Expected Behavior**

The approver and the comment is visible if requisition is rejected by system.
Rejected by system is displayed in the requisition list, e. g. Jack Link (rejected by system).

**Steps to Reproduce the Bug**

1. Go to 'cost center management'
2. Add buyer to the cost center
3. Order something with this buyer so he has a pending order on the selected cost center
4. Remove the buyer from the cost center although he still has a pending order
5. Approve the requisition with all approvers

**Environment Details**

- Desktop: 
  - Browser: Chrome
  - Project Code Version: PWA 1.4 Public Demo Server

**Additional Context, like Screenshots, Log File Snippets etc.**

Current:
<img width="245" alt="2021-12-14 09_24_16-My Account _ Intershop PWA" src="https://user-images.githubusercontent.com/66066967/145961648-62907a26-a478-4164-b6e8-23a21c11ed53.png">

IAD:
<img width="289" alt="2021-12-14 09_24_46-Rejected Requisition" src="https://user-images.githubusercontent.com/66066967/145961667-13559ba5-a901-49fd-96de-30dec795c88d.png">

[AB#72093](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/72093)

**Comment by SGrueber** [comment]
ICM Update is needed
